import { useState } from "react";
import { motion } from "framer-motion";
import { PublicLayout } from "@/components/layout/PublicLayout";
import { Input } from "@/components/ui/input";
import { Search, ChevronDown } from "lucide-react";
import { LedgerHero, LedgerSection, LedgerHeader, rise } from "@/components/ledger";
import { cn } from "@/lib/utils";

const categories = [
  { title: "Getting started", body: "Learn the basics of The 3rd Academy platform", n: 12 },
  { title: "The Behavioral Evidence Report", body: "Understanding your record — how it is built and released", n: 8 },
  { title: "MentorLink", body: "Working with mentors and observation sessions", n: 15 },
  { title: "For employers", body: "Using T3X Exchange and reading Behavioral Evidence Reports", n: 10 },
  { title: "For schools", body: "Civic Access Lab implementation guides", n: 7 },
  { title: "Account & billing", body: "Manage your account, subscription, and preferences", n: 9 },
];

const faqs = [
  {
    category: "General",
    questions: [
      { q: "What is The 3rd Academy?", a: "A behavioral readiness platform that keeps a dated record of observed conduct — how a candidate acts across workplace-pressure situations, mentor-observed, over time. Not a certifier. A registrar." },
      { q: "How is this different from traditional certifications?", a: "Certifications say what you passed. A Behavioral Evidence Report is a dated record of how you conducted yourself when the work stopped going to plan. Observation-based, not exam-based." },
      { q: "How long does it take to build a Behavioral Evidence Report?", a: "The record accrues at the pace of your work. Most participants have a first releasable entry within four to eight weeks. There is no fixed schedule — evidence takes the time it takes." },
    ],
  },
  {
    category: "Candidates",
    questions: [
      { q: "How do I get started as a candidate?", a: "Upload your résumé through Entry A. You will be matched with a mentor within 48 hours and begin building your record from the first observed situation." },
      { q: "What happens during a MentorLink session?", a: "You work on a realistic task or scenario while a mentor observes your conduct. The observation — not a score — is documented in your Growth Log and, when appropriate, released into your BER." },
      { q: "Is there a cost for candidates?", a: "Civic Access Lab is free for students through participating schools. For professionals, entry is free; TalentVisa (extended visibility) is an optional paid tier." },
    ],
  },
  {
    category: "Employers",
    questions: [
      { q: "How do I access candidate records?", a: "Through the T3X Exchange reading room, once a candidate has released their Behavioral Evidence Report to your organization." },
      { q: "What makes the record reliable?", a: "It is written by trained industry mentors, dated, situational, and open to challenge. Nothing in it is generated by a model; every entry is auditable." },
      { q: "Can we integrate with our ATS?", a: "Yes — the Subscriber tier includes API access to the register, with adapters for the major applicant tracking systems." },
    ],
  },
  {
    category: "Schools",
    questions: [
      { q: "What is Civic Access Lab?", a: "A free institutional programme that lets schools begin the record before graduation, using classroom-work moments as the first situations of observation." },
      { q: "How do we implement Civic Access Lab?", a: "Sign a partnership agreement, train facilitators, and launch — usually within one semester. All curriculum and platform access is provided." },
      { q: "Who can access Civic Access Lab?", a: "Civic Access Lab is open to students at any level of study — secondary, post-secondary, full-time or part-time. What matters is that you are studying, not what stage you have reached." },
    ],
  },
];

const Help = () => {
  const [searchQuery, setSearchQuery] = useState("");
  const [openFaq, setOpenFaq] = useState<string | null>(null);

  const filtered = faqs
    .map((cat) => ({
      ...cat,
      questions: cat.questions.filter(
        (q) =>
          !searchQuery ||
          q.q.toLowerCase().includes(searchQuery.toLowerCase()) ||
          q.a.toLowerCase().includes(searchQuery.toLowerCase())
      ),
    }))
    .filter((cat) => cat.questions.length > 0);

  return (
    <PublicLayout>
      <LedgerHero
        eyebrow="§ Help · Reading Room"
        meta="Search the record"
        stamp="Answers within 24h"
        title={
          <>
            <span className="block">How can</span>
            <span className="block italic display-serif-italic">we help</span>
            <span className="block ink-vermilion">you?</span>
          </>
        }
        ledeSide={
          <div>
            <div className="mono-label text-foreground/60 mb-3">Search</div>
            <div className="relative border-b-2 border-foreground">
              <Search className="absolute right-0 top-1/2 -translate-y-1/2 w-5 h-5 text-foreground/60" />
              <Input
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Type your question…"
                className="rounded-none border-0 bg-transparent px-0 py-4 text-lg display-serif focus-visible:ring-0 pr-8"
              />
            </div>
          </div>
        }
      />

      {/* Categories */}
      <LedgerSection first>
        <LedgerHeader eyebrow="§ I · Sections" side="Browse by topic.">
          Six <span className="italic display-serif-italic">sections</span>.
        </LedgerHeader>

        <div className="grid md:grid-cols-3 border-t-2 border-foreground border-b border-foreground/40">
          {categories.map((c, i) => (
            <motion.div
              key={c.title}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={rise}
              custom={i}
              className={
                "p-8 hover:bg-foreground/[0.025] transition-colors " +
                (i % 3 !== 0 ? "md:border-l border-foreground/25 " : "") +
                (i >= 3 ? "border-t border-foreground/25" : "")
              }
            >
              <div className="ledger-num text-4xl text-foreground mb-3">
                {String(i + 1).padStart(2, "0")}
              </div>
              <h3 className="display-serif text-2xl text-foreground mb-2">{c.title}</h3>
              <p className="text-foreground/80 text-[0.9375rem] mb-4 leading-relaxed">{c.body}</p>
              <div className="mono-label text-foreground/50">{c.n} entries</div>
            </motion.div>
          ))}
        </div>
      </LedgerSection>

      {/* FAQs */}
      <LedgerSection>
        <LedgerHeader eyebrow="§ II · Frequently asked">
          Frequently <span className="italic display-serif-italic">asked</span>.
        </LedgerHeader>

        <div className="space-y-14">
          {filtered.map((cat) => (
            <div key={cat.category}>
              <div className="mono-label text-foreground/60 pb-3 mb-6 border-b border-foreground/25">
                {cat.category}
              </div>
              <div className="space-y-2">
                {cat.questions.map((q) => {
                  const id = q.q.slice(0, 40);
                  const isOpen = openFaq === id;
                  return (
                    <div
                      key={id}
                      className={cn(
                        "border-b border-foreground/20 group",
                        isOpen && "bg-foreground/[0.02]"
                      )}
                    >
                      <button
                        onClick={() => setOpenFaq(isOpen ? null : id)}
                        className="w-full flex items-baseline justify-between gap-6 py-5 text-left"
                      >
                        <span className="display-serif text-xl md:text-2xl text-foreground group-hover:italic transition-all">
                          {q.q}
                        </span>
                        <ChevronDown
                          className={cn(
                            "w-5 h-5 text-foreground flex-shrink-0 transition-transform",
                            isOpen && "rotate-180"
                          )}
                        />
                      </button>
                      {isOpen && (
                        <div className="pb-6 pr-10 text-foreground/85 leading-[1.75] text-[1.0625rem]">
                          {q.a}
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          ))}
          {filtered.length === 0 && (
            <p className="marginalia">No entries match that search. Try a broader term.</p>
          )}
        </div>
      </LedgerSection>
    </PublicLayout>
  );
};

export default Help;
