#!/usr/bin/env python3
"""Generate the SQL that loads CORR-006 Annexes A, B and C as issued content.

WHY THIS EXISTS RATHER THAN A HAND-WRITTEN MIGRATION. SOP-002 Stage 0.2:
never transcribe. Annex A holds the only words the Stage 1 engine is
permitted to add, Annex C holds the crisis line a distressed participant is
shown, and both render to a participant exactly as written. Retyping them
into a migration risks a drift no test would catch, because nothing in the
build knows what the instrument says — only what was typed.

So the text is SLICED from the instrument on disk and the SQL is generated.
The generated migration carries a sha256 of every extracted block and
refuses to commit if what it stored does not hash to what was sliced, which
makes a later hand-edit of the migration fail loudly instead of quietly
changing participant-facing wording.

Run:  python3 scripts/generate_corr006_annex_load.py > <migration>.sql
"""

import hashlib
import re
import sys

DOC = "docs/d1-execution/T3A-D1-EXEC-CORR-006-Post-Close-Out.md"


def sl(text: str, start: str, end: str) -> str:
    return text[text.index(start): text.index(end)].rstrip()


def blockquotes(section: str) -> list[str]:
    """Every run of consecutive '>' lines, with the marker stripped."""
    out = []
    for group in re.findall(r"(?:^>.*(?:\n>.*)*)", section, re.M):
        lines = []
        for line in group.split("\n"):
            lines.append(line[2:] if line.startswith("> ") else line[1:])
        out.append("\n".join(lines).strip())
    return out


def h(s: str) -> str:
    return hashlib.sha256(s.encode()).hexdigest()


def lit(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main() -> int:
    doc = open(DOC, encoding="utf-8").read()

    annex_a = sl(doc, "## Annex A", "## Annex B")
    annex_b = sl(doc, "## Annex B", "## Annex C")
    annex_c = sl(doc, "## Annex C", "## Annex D")

    a3 = annex_a[annex_a.index("### A.3"):]
    quotes_a = blockquotes(a3)
    if len(quotes_a) != 3:
        print(f"A.3 holds {len(quotes_a)} quoted blocks, expected exactly three "
              f"(opening, closing, support line).", file=sys.stderr)
        return 1
    opening, closing, support_line = quotes_a

    c3 = annex_c[annex_c.index("### C.3"): annex_c.index("### C.4")]
    quotes_c = blockquotes(c3)
    if len(quotes_c) != 1:
        print(f"C.3 holds {len(quotes_c)} quoted blocks, expected exactly one.", file=sys.stderr)
        return 1
    support_information = quotes_c[0]

    # C4a states the Stage 3 pre-start wording inline, in italics, after a
    # colon. Extracted by its own anchor rather than by position in a table.
    m = re.search(
        r"At Stage 3 it reads, exactly:\*\* \*(.+?)\*\s*\|", annex_c, re.S)
    if not m:
        print("C4a's exact Stage 3 wording could not be located.", file=sys.stderr)
        return 1
    stage3_wording = " ".join(m.group(1).split())

    objects = [
        dict(
            identifier="T3A-S1-DELIVERY-SPEC-001",
            family="ai_administration_ruleset",
            title="Stage 1 Delivery Specification",
            slot="prompt_ref_version_id",
            verbatim=annex_a,
            extra={
                "opening": opening,
                "closing": closing,
                "support_line": support_line,
                "max_minutes_rule":
                    "the source's max_seconds divided by sixty, rounded down",
            },
            issued_under="T3A-D1-EXEC-CORR-006 Annex A",
        ),
        dict(
            identifier="T3A-S1-ADMIN-CONFIG-001",
            family="configuration",
            title="Stage 1 Administration Configuration",
            slot="admin_config_version_id",
            verbatim=annex_b,
            extra={},
            issued_under="T3A-D1-EXEC-CORR-006 Annex B",
        ),
        dict(
            identifier="T3A-PARTICIPANT-SAFETY-001",
            family="configuration",
            title="Participant Safety Configuration",
            slot="safety_config_version_id",
            verbatim=annex_c,
            extra={
                "support_information": support_information,
                "stage3_pre_start_wording": stage3_wording,
            },
            issued_under="T3A-D1-EXEC-CORR-006 Annex C",
        ),
    ]

    w = sys.stdout.write
    w("""-- =====================================================================
-- CORR-006 Section 4, CX-10 / CX-11 / CX-12 — Annexes A, B and C load as
-- issued content, and the four provenance slots are named
--
-- GENERATED BY scripts/generate_corr006_annex_load.py. DO NOT HAND-EDIT.
--
-- SOP-002 Stage 0.2: never transcribe. Annex A holds the only words the
-- Stage 1 engine may add, and Annex C holds the crisis line a distressed
-- participant is shown. Both render to a participant exactly as written, so
-- neither was retyped: the generator slices them out of the instrument on
-- disk and emits this file. Every block carries a sha256 taken at slice
-- time, and the assertion at the end recomputes it from what was STORED. A
-- later hand-edit of this migration therefore fails to commit rather than
-- quietly changing what a participant reads.
--
-- WHAT THIS DOES NOT DO. It does not make a real Stage 1 run possible.
-- Three of the four provenance slots are filled by this instrument; the
-- fourth, the model reference, is the delivery engine's own identifier,
-- version and code hash, which CX-08 makes the build's to supply and which
-- does not exist yet. A real run still refuses for want of it, and the
-- refusal is named rather than left as a NOT NULL violation.
--
-- The demonstration objects under 20261061000000 are NOT relabelled,
-- reused or deleted (CX-09). They keep synthetic_test_only = true and the
-- bar that refuses a non-demonstration run citing them.
-- =====================================================================

set search_path = public;

-- ---------------------------------------------------------------------
-- 1. The three issued objects
-- ---------------------------------------------------------------------

""")

    for o in objects:
        body = {"source_identifier": o["identifier"],
                "title": o["title"],
                "issued_under": o["issued_under"],
                "verbatim": o["verbatim"],
                "source_version_hash": h(o["verbatim"])}
        for k, v in o["extra"].items():
            body[k] = v
            body[k + "_hash"] = h(v)

        w(f"-- {o['identifier']} — {o['title']}, {o['issued_under']}\n")
        w("DO $load$\nDECLARE v_obj uuid;\nBEGIN\n")
        w("  SELECT content_object_id INTO v_obj FROM public.t3a_content_object\n")
        w(f"   WHERE identifier = {lit(o['identifier'])};\n\n")
        w("  IF v_obj IS NULL THEN\n")
        w("    INSERT INTO public.t3a_content_object (identifier, family, title, dimension_id)\n")
        w(f"    VALUES ({lit(o['identifier'])}, {lit(o['family'])}::public.t3a_content_family,\n")
        w(f"            {lit(o['title'])}, 'D1')\n")
        w("    RETURNING content_object_id INTO v_obj;\n")
        w("  END IF;\n\n")
        w("  IF NOT EXISTS (SELECT 1 FROM public.t3a_d1_content_version\n")
        w("                  WHERE content_object_id = v_obj AND superseded_by IS NULL) THEN\n")
        w("    INSERT INTO public.t3a_d1_content_version (content_object_id, version_no, body)\n")
        w("    VALUES (v_obj, 1, jsonb_build_object(\n")
        pairs = []
        for k, v in body.items():
            pairs.append(f"      {lit(k)}, {lit(v)}")
        w(",\n".join(pairs))
        w("));\n")
        w("  END IF;\n")
        w("END;\n$load$;\n\n")

    w("""-- ---------------------------------------------------------------------
-- 2. CX-10 — the four provenance slots, named, with no field renamed
--
-- Section 8.1 names three references and the run table has four columns.
-- The mapping is recorded as ROWS so that "which issued object belongs in
-- prompt_ref_version_id" is a fact the guard reads, not a rule written
-- twice. The column names are untouched (Standing Rule 4): what is added is
-- a register saying what each one holds.
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.t3a_d1_s1_provenance_slot (
  slot_column        text PRIMARY KEY,
  holds              text NOT NULL,
  issued_identifier  text,
  supplied_by        text NOT NULL,
  issued_under       text NOT NULL
);

COMMENT ON TABLE public.t3a_d1_s1_provenance_slot IS
  'CX-10. What each of the four provenance columns on t3a_d1_ai_administration_run holds, and who supplies it. No column is renamed; this names them. issued_identifier is NULL for the model reference because the delivery engine that fills it is the build''s to supply under CX-08 and does not exist yet — a null here is the honest state, and t3a_d1_s1_production_provenance refuses a real run while it stands.';

INSERT INTO public.t3a_d1_s1_provenance_slot
  (slot_column, holds, issued_identifier, supplied_by, issued_under)
VALUES
  ('model_ref_version_id',
   'The engine''s identifier, version and code hash',
   NULL,
   'The build, under CX-08',
   'T3A-D1-EXEC-CORR-006 Section 4.2, CX-10'),
  ('prompt_ref_version_id',
   'Annex A — the Stage 1 Delivery Specification',
   'T3A-S1-DELIVERY-SPEC-001',
   'T3A-D1-EXEC-CORR-006',
   'T3A-D1-EXEC-CORR-006 Section 4.2, CX-10'),
  ('admin_config_version_id',
   'Annex B — the Stage 1 Administration Configuration',
   'T3A-S1-ADMIN-CONFIG-001',
   'T3A-D1-EXEC-CORR-006',
   'T3A-D1-EXEC-CORR-006 Section 4.2, CX-10'),
  ('safety_config_version_id',
   'Annex C — the Participant Safety Configuration',
   'T3A-PARTICIPANT-SAFETY-001',
   'T3A-D1-EXEC-CORR-006',
   'T3A-D1-EXEC-CORR-006 Section 4.2, CX-10')
ON CONFLICT (slot_column) DO UPDATE SET
  holds             = EXCLUDED.holds,
  issued_identifier = EXCLUDED.issued_identifier,
  supplied_by       = EXCLUDED.supplied_by,
  issued_under      = EXCLUDED.issued_under;

ALTER TABLE public.t3a_d1_s1_provenance_slot ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS t3a_d1_s1_provenance_slot_read ON public.t3a_d1_s1_provenance_slot;
CREATE POLICY t3a_d1_s1_provenance_slot_read
  ON public.t3a_d1_s1_provenance_slot FOR SELECT TO authenticated USING (true);

-- ---------------------------------------------------------------------
-- 3. CX-12 — what a real run may cite, reported rather than inferred
--
-- "A real run then refuses only for the reasons Section 8.1 and the
-- activation gate already give — never for missing content." Three of the
-- four are now present, so the only missing content is the engine, and this
-- function says so by name instead of leaving a caller to read a NOT NULL
-- violation and guess.
-- ---------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.t3a_d1_s1_production_provenance()
RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $fn$
  WITH slot AS (
    SELECT s.slot_column, s.holds, s.issued_identifier, s.supplied_by,
           cv.content_version_id,
           cv.body ->> 'source_version_hash' AS version_hash
      FROM public.t3a_d1_s1_provenance_slot s
      LEFT JOIN public.t3a_content_object co
        ON co.identifier = s.issued_identifier
      LEFT JOIN public.t3a_d1_content_version cv
        ON cv.content_object_id = co.content_object_id AND cv.superseded_by IS NULL
  )
  SELECT jsonb_build_object(
    'slots', (SELECT jsonb_agg(jsonb_build_object(
                'slot_column', slot.slot_column,
                'holds', slot.holds,
                'issued_identifier', slot.issued_identifier,
                'supplied_by', slot.supplied_by,
                'loaded', slot.content_version_id IS NOT NULL,
                'version_id', slot.content_version_id,
                'version_hash', slot.version_hash) ORDER BY slot.slot_column)
               FROM slot),
    'all_four_present', (SELECT bool_and(slot.content_version_id IS NOT NULL) FROM slot),
    'missing', (SELECT coalesce(jsonb_agg(slot.slot_column ORDER BY slot.slot_column), '[]'::jsonb)
                  FROM slot WHERE slot.content_version_id IS NULL),
    'refusal_code', CASE WHEN (SELECT bool_and(slot.content_version_id IS NOT NULL) FROM slot)
                         THEN NULL ELSE 'S1_PRODUCTION_PROVENANCE_INCOMPLETE' END,
    'remedy', CASE WHEN (SELECT bool_and(slot.content_version_id IS NOT NULL) FROM slot)
                   THEN NULL
                   ELSE 'The delivery engine''s model reference is the build''s to supply under CX-08 '
                        'and is not built yet. Until it exists, a real Stage 1 run has no fourth '
                        'provenance object to cite.' END);
$fn$;

COMMENT ON FUNCTION public.t3a_d1_s1_production_provenance() IS
  'CX-12. Which of the four Stage 1 provenance objects a real run can cite today, and which cannot, by name. Reads the CX-10 slot register rather than restating the mapping.';

GRANT EXECUTE ON FUNCTION public.t3a_d1_s1_production_provenance() TO authenticated;

-- ---------------------------------------------------------------------
-- 4. Assert the text, from what was STORED
--
-- Recomputed from the database, not from the generator's own variables, so
-- this catches a hand-edit of the SQL above as well as a load that dropped
-- a character.
-- ---------------------------------------------------------------------

DO $verify$
DECLARE
  r       record;
  v_n     int := 0;
  v_key   text;
BEGIN
  FOR r IN
    SELECT co.identifier, cv.body
      FROM public.t3a_content_object co
      JOIN public.t3a_d1_content_version cv
        ON cv.content_object_id = co.content_object_id AND cv.superseded_by IS NULL
     WHERE co.identifier IN ('T3A-S1-DELIVERY-SPEC-001', 'T3A-S1-ADMIN-CONFIG-001',
                             'T3A-PARTICIPANT-SAFETY-001')
  LOOP
    v_n := v_n + 1;

    -- Every <key>_hash in the body must be the sha256 of <key>.
    FOR v_key IN
      SELECT k FROM jsonb_object_keys(r.body) k WHERE k LIKE '%\\_hash'
    LOOP
      DECLARE
        v_subject text := left(v_key, length(v_key) - 5);
        v_stored  text := r.body ->> v_key;
        v_text    text;
      BEGIN
        -- source_version_hash names 'verbatim', not a key called 'source_version'.
        IF v_key = 'source_version_hash' THEN v_subject := 'verbatim'; END IF;
        v_text := r.body ->> v_subject;

        IF v_text IS NULL THEN
          RAISE EXCEPTION 'ANNEX_HASH_HAS_NO_SUBJECT: % carries % but no key %', r.identifier, v_key, v_subject;
        END IF;
        IF encode(sha256(convert_to(v_text, 'UTF8')), 'hex') IS DISTINCT FROM v_stored THEN
          RAISE EXCEPTION 'ANNEX_TEXT_DRIFTED: %.% does not hash to its stored %. Participant-facing wording is not paraphrased.', r.identifier, v_subject, v_key;
        END IF;
      END;
    END LOOP;
  END LOOP;

  IF v_n <> 3 THEN
    RAISE EXCEPTION 'ANNEX_LOAD_INCOMPLETE: % of the three annex objects are loaded.', v_n;
  END IF;

  RAISE NOTICE 'Annexes A, B and C loaded; every stored block hashes to itself.';
END;
$verify$;

-- ---------------------------------------------------------------------
-- 5. CX-09 — the demonstration objects are untouched, asserted
-- ---------------------------------------------------------------------

DO $cx09$
DECLARE v_n int; v_bar int;
BEGIN
  SELECT count(*) INTO v_n
    FROM public.t3a_content_object co
    JOIN public.t3a_d1_content_version cv
      ON cv.content_object_id = co.content_object_id AND cv.superseded_by IS NULL
   WHERE co.identifier LIKE 'SYNTHETIC\\_TEST\\_ONLY-D1-%'
     AND (cv.body ->> 'synthetic_test_only')::boolean IS TRUE;

  -- Named exactly, and named from reading pg_trigger rather than from a
  -- comment: the first draft asserted
  -- t3a_d1_ai_administration_run_synthetic_bar_trg, which I inferred from
  -- the prose in 20261061000000. The trigger is
  -- t3a_d1_ai_run_synthetic_bar_trg, so the whole migration refused to
  -- commit. That is the assertion working, and it is also AS-41 again:
  -- name the object, and read the object's name from the object.
  SELECT count(*) INTO v_bar
    FROM pg_trigger t JOIN pg_proc p ON p.oid = t.tgfoid
   WHERE NOT t.tgisinternal
     AND t.tgrelid = 'public.t3a_d1_ai_administration_run'::regclass
     AND t.tgname = 't3a_d1_ai_run_synthetic_bar_trg'
     AND p.proname = 't3a_d1_ai_run_synthetic_bar';

  IF v_n <> 4 THEN
    RAISE EXCEPTION 'CX09_DEMONSTRATION_OBJECTS_DISTURBED: % objects still marked synthetic_test_only, expected four.', v_n;
  END IF;
  IF v_bar <> 1 THEN
    RAISE EXCEPTION 'CX09_SYNTHETIC_BAR_MISSING: the trigger refusing a real run that cites demonstration provenance is not on the run table.';
  END IF;

  RAISE NOTICE 'CX-09: four demonstration objects intact and still barred from a real run.';
END;
$cx09$;

-- ---------------------------------------------------------------------
-- 6. What this leaves open
-- ---------------------------------------------------------------------

INSERT INTO public.t3a_d1_build_conflict_register
  (entry_id, opened_by, scope, classification, status, blocked_on, note)
VALUES
  ('CORR-006/CX-12/annex-c-registered-under-one-dimension',
   'CORR-006 Section 4, while loading Annex C',
   'The scope a safety configuration is registered with',
   'recorded rather than decided — the content register has no wider scope to use',
   'open',
   'Founder: confirm that one registration of T3A-PARTICIPANT-SAFETY-001 under D1 is intended to '
   || 'govern every dimension, or direct that the register carry a scope wider than a dimension.',
   'Annex C says of itself that it "governs every Stage of every dimension". Every row in '
   || 't3a_content_object carries a single dimension_id, and there is no value meaning "all". '
   || 'T3A-PARTICIPANT-SAFETY-001 is therefore registered under D1, which is where it is cited from '
   || 'today and is the only dimension that exists. '
   || 'WHY THIS IS NOT NOTHING. The obvious alternatives were both worse. Loading a copy per '
   || 'dimension would create several objects where the founder issued one, and the copies would '
   || 'drift — a safety configuration is the last content that should exist in more than one place. '
   || 'Adding an "all dimensions" sentinel to the register would change what a dimension_id means '
   || 'for every object in the schema, which is a doctrine change and the DEVELOPER JUDGMENT '
   || 'BOUNDARY reserves those. So one object, registered where it is used, and the discrepancy '
   || 'between its stated scope and its registered scope recorded here rather than papered over. '
   || 'NOTHING IS BLOCKED: D2 does not exist yet, so no Stage of any other dimension is currently '
   || 'unable to cite it.')
ON CONFLICT (entry_id) DO UPDATE SET
  opened_by = EXCLUDED.opened_by, scope = EXCLUDED.scope,
  classification = EXCLUDED.classification, status = EXCLUDED.status,
  blocked_on = EXCLUDED.blocked_on, note = EXCLUDED.note;
""")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
