-- =====================================================================
-- CORR-006 Section 4, CX-10 / CX-11 / CX-12 — Annexes A, B and C load as
-- issued content, and the four provenance slots are named
--
-- GENERATED BY scripts/generate_corr006_annex_load.py. DO NOT HAND-EDIT.
--
-- SOP-002 Stage 0.2: never transcribe. Annex A holds the only words the
-- Stage 1 engine may add, and Annex C holds the crisis line a distressed
-- participant is shown. Both render to a participant exactly as written, so
-- neither was retyped: the generator slices them out of the instrument on
-- disk and emits this file. Every block carries a sha256 taken at slice
-- time, and the assertion at the end recomputes it from what was STORED. A
-- later hand-edit of this migration therefore fails to commit rather than
-- quietly changing what a participant reads.
--
-- WHAT THIS DOES NOT DO. It does not make a real Stage 1 run possible.
-- Three of the four provenance slots are filled by this instrument; the
-- fourth, the model reference, is the delivery engine's own identifier,
-- version and code hash, which CX-08 makes the build's to supply and which
-- does not exist yet. A real run still refuses for want of it, and the
-- refusal is named rather than left as a NOT NULL violation.
--
-- The demonstration objects under 20261061000000 are NOT relabelled,
-- reused or deleted (CX-09). They keep synthetic_test_only = true and the
-- bar that refuses a non-demonstration run citing them.
-- =====================================================================

set search_path = public;

-- ---------------------------------------------------------------------
-- 1. The three issued objects
-- ---------------------------------------------------------------------

-- T3A-S1-DELIVERY-SPEC-001 — Stage 1 Delivery Specification, T3A-D1-EXEC-CORR-006 Annex A
DO $load$
DECLARE v_obj uuid;
BEGIN
  SELECT content_object_id INTO v_obj FROM public.t3a_content_object
   WHERE identifier = 'T3A-S1-DELIVERY-SPEC-001';

  IF v_obj IS NULL THEN
    INSERT INTO public.t3a_content_object (identifier, family, title, dimension_id)
    VALUES ('T3A-S1-DELIVERY-SPEC-001', 'ai_administration_ruleset'::public.t3a_content_family,
            'Stage 1 Delivery Specification', 'D1')
    RETURNING content_object_id INTO v_obj;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.t3a_d1_content_version
                  WHERE content_object_id = v_obj AND superseded_by IS NULL) THEN
    INSERT INTO public.t3a_d1_content_version (content_object_id, version_no, body)
    VALUES (v_obj, 1, jsonb_build_object(
      'source_identifier', 'T3A-S1-DELIVERY-SPEC-001',
      'title', 'Stage 1 Delivery Specification',
      'issued_under', 'T3A-D1-EXEC-CORR-006 Annex A',
      'verbatim', '## Annex A — Stage 1 Delivery Specification

**Identifier** `T3A-S1-DELIVERY-SPEC-001`  |  Loads as the Stage 1 **prompt text** (`prompt_ref`)  |  Applies to every Stage 1 source

### A.1 What the engine does, in order

1. Show the **opening** at A.3.
2. Show the source''s block *"The situation, as the participant meets it,"* verbatim.
3. Show the source''s reveals in order, R1 onward, verbatim, one at a time.
4. After each reveal, accept one typed response. **The participant submits it to continue.**
5. After the last response, show the **closing** at A.3.

### A.2 Fixed rules

| # | Rule |
| --- | --- |
| DS-1 | **Nothing is generated, paraphrased, reordered, summarized or added** beyond the words at A.3 |
| DS-2 | **A submitted response cannot be edited or recalled.** Later reveals change what the participant knows, and the account-test reveal depends on the earlier account standing as given |
| DS-3 | **No feedback, no correct answer, no indication of how a response was received** |
| DS-4 | **Progress is shown only as the part number** — for example *"Part 2"* — never as a bar, a percentage or a count of parts remaining |
| DS-5 | **The source title, source sheet and applicability are never shown** |
| DS-6 | **The participant never sees a determination, statement, record or anything a confirmer does** |

### A.3 The only words the engine adds

**Opening:**

> In this part, you will read a workplace situation on screen, one stage at a time. After each stage, type what you would do or say, in your own words. There is no score. Write as you would at work.
>
> You have up to {max_minutes} minutes. Once you submit a response, you move on and cannot go back to change it.
>
> Nobody reads what you type while you are typing it. If at any point you feel distressed, you can stop: use Stop at the top of the screen. Stopping does not use up one of your attempts.
>
> If you are in crisis or thinking about harming yourself, call or text 9-8-8, any time, day or night. In an emergency, call 9-1-1.

**Closing:**

> Thank you. Your responses have been saved exactly as you wrote them. An authorized person will read them. Nothing is decided automatically.
>
> If you need support, call or text 9-8-8, any time. In an emergency, call 9-1-1.

**On every screen, beside the Stop control:**

> Need support? Call or text 9-8-8. Emergency: 9-1-1.

`{max_minutes}` is the source''s `max_seconds` divided by sixty, rounded down.

---',
      'source_version_hash', 'bdf5a0a753e8aaec146428c078bb98f9a00c7b5022cc1b086e480421acc1591a',
      'opening', 'In this part, you will read a workplace situation on screen, one stage at a time. After each stage, type what you would do or say, in your own words. There is no score. Write as you would at work.

You have up to {max_minutes} minutes. Once you submit a response, you move on and cannot go back to change it.

Nobody reads what you type while you are typing it. If at any point you feel distressed, you can stop: use Stop at the top of the screen. Stopping does not use up one of your attempts.

If you are in crisis or thinking about harming yourself, call or text 9-8-8, any time, day or night. In an emergency, call 9-1-1.',
      'opening_hash', '7991c786dc4538ade57b6bfed5d41a97e470474eaebef2656cb7ccb517501a65',
      'closing', 'Thank you. Your responses have been saved exactly as you wrote them. An authorized person will read them. Nothing is decided automatically.

If you need support, call or text 9-8-8, any time. In an emergency, call 9-1-1.',
      'closing_hash', 'f30de51bcbaeb1a9fd0671f0f69cd4123a9e3cf43227849309a43ab1a6e118ec',
      'support_line', 'Need support? Call or text 9-8-8. Emergency: 9-1-1.',
      'support_line_hash', '0dd5510c3f6dde042e58b4b438411bb80b7788958e895c0c6c042ce8e74b8fc8',
      'max_minutes_rule', 'the source''s max_seconds divided by sixty, rounded down',
      'max_minutes_rule_hash', '92f24cbf9db74679d07dc3529b6b683437d26cfbe6b16ae63de3a0c75f537a1e'));
  END IF;
END;
$load$;

-- T3A-S1-ADMIN-CONFIG-001 — Stage 1 Administration Configuration, T3A-D1-EXEC-CORR-006 Annex B
DO $load$
DECLARE v_obj uuid;
BEGIN
  SELECT content_object_id INTO v_obj FROM public.t3a_content_object
   WHERE identifier = 'T3A-S1-ADMIN-CONFIG-001';

  IF v_obj IS NULL THEN
    INSERT INTO public.t3a_content_object (identifier, family, title, dimension_id)
    VALUES ('T3A-S1-ADMIN-CONFIG-001', 'configuration'::public.t3a_content_family,
            'Stage 1 Administration Configuration', 'D1')
    RETURNING content_object_id INTO v_obj;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.t3a_d1_content_version
                  WHERE content_object_id = v_obj AND superseded_by IS NULL) THEN
    INSERT INTO public.t3a_d1_content_version (content_object_id, version_no, body)
    VALUES (v_obj, 1, jsonb_build_object(
      'source_identifier', 'T3A-S1-ADMIN-CONFIG-001',
      'title', 'Stage 1 Administration Configuration',
      'issued_under', 'T3A-D1-EXEC-CORR-006 Annex B',
      'verbatim', '## Annex B — Stage 1 Administration Configuration

**Identifier** `T3A-S1-ADMIN-CONFIG-001`  |  Loads as the Stage 1 **administration configuration** (`configuration_ref`)

| # | Rule |
| --- | --- |
| AC-B1 | **A run may begin only when** the participant''s identity is verified; a valid, current, in-scope consent record exists; Stage entry has passed; the attempt cap of three is not reached; no cooldown is in force; and any accommodation is settled and recorded. **Any accommodation is settled before the run, never during it** |
| AC-B2 | **Sequence:** as Annex A, fixed |
| AC-B3 | **Time allowed:** up to the source''s `max_seconds`, counted from when the situation text is first shown. **No minimum is imposed on the participant.** `min_seconds` is recorded with the run for the confirmer and for scheduling. A forced wait would add pressure the situation does not call for |
| AC-B3a | **The ten loaded windows must be exactly these.** The issued file stores each Stage 1 window with both numbers in `max_seconds` and an empty `min_seconds`, so the loaded values are checked here: S1-001 600 and 1,500; S1-002 360 and 900; S1-003 360 and 900; S1-004 480 and 1,500; S1-005 360 and 1,200; S1-006 480 and 1,200; S1-007 360 and 1,000; S1-008 480 and 1,200; S1-009 480 and 1,200; S1-010 480 and 1,200 — minimum first. **Where a loaded value differs, the run for that source refuses until corrected** |
| AC-B4 | **When five minutes remain,** show once: *"About five minutes remain."* No running clock is shown |
| AC-B5 | **At `max_seconds` the run closes.** Submitted responses are kept. Text typed but not submitted is not captured. A reveal shown but not answered is recorded as `no response`; a reveal not reached is recorded as `never asked`. **The run is a completed observation** |
| AC-B6 | **No pause is available.** Stop ends the run under CX-28 |
| AC-B7 | **Disconnection:** the run holds at the current reveal, with submitted responses intact, and resumes there if the participant returns before `max_seconds`. If they do not return, the run ends as **"Withdrawal after observation begins, before commit"** — unless the platform logs a fault on its own side, in which case it is a **"Technical or platform failure."** This closes the route of abandoning a run to reset it without cooldown |
| AC-B8 | **Responses:** stored exactly as typed. **No content limit is imposed on the participant.** Any technical ceiling must exceed any plausible response and, if reached, **refuses visibly rather than truncating** |
| AC-B9 | **After the run,** responses pass to the Stage 1 Confirmation Workbench for an authorized confirmer, under T3A-D1-EXEC-001 Section 8.1.1 and Annex C |
| AC-B10 | **Provenance** recorded on every run: all four provenance objects with versions and hashes; start and end; a timestamp for every reveal; `source_version_id`; the rendered instance |

---',
      'source_version_hash', 'f8748d69fd7c8d3af25e34cb7621f5b9644387eef6479ad04fdc56ad308b371b'));
  END IF;
END;
$load$;

-- T3A-PARTICIPANT-SAFETY-001 — Participant Safety Configuration, T3A-D1-EXEC-CORR-006 Annex C
DO $load$
DECLARE v_obj uuid;
BEGIN
  SELECT content_object_id INTO v_obj FROM public.t3a_content_object
   WHERE identifier = 'T3A-PARTICIPANT-SAFETY-001';

  IF v_obj IS NULL THEN
    INSERT INTO public.t3a_content_object (identifier, family, title, dimension_id)
    VALUES ('T3A-PARTICIPANT-SAFETY-001', 'configuration'::public.t3a_content_family,
            'Participant Safety Configuration', 'D1')
    RETURNING content_object_id INTO v_obj;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.t3a_d1_content_version
                  WHERE content_object_id = v_obj AND superseded_by IS NULL) THEN
    INSERT INTO public.t3a_d1_content_version (content_object_id, version_no, body)
    VALUES (v_obj, 1, jsonb_build_object(
      'source_identifier', 'T3A-PARTICIPANT-SAFETY-001',
      'title', 'Participant Safety Configuration',
      'issued_under', 'T3A-D1-EXEC-CORR-006 Annex C',
      'verbatim', '## Annex C — Participant Safety Configuration

**Identifier** `T3A-PARTICIPANT-SAFETY-001`  |  Loads as the Stage 1 **safety configuration**, and governs every Stage of every dimension

**Status.** Issued by the founder. **Counsel reviews it before real observation is activated at any Stage.** It loads now; activation remains separately gated.

### C.1 Principles

| # | Principle |
| --- | --- |
| C1 | **A participant''s wellbeing comes before any observation.** Any observation can be stopped at any moment, by the participant or the mentor, and stopping never uses up an attempt |
| C2 | **A disclosure is never evidence.** Anything a participant says or writes about harm, distress or risk to themselves or others is never captured as a determination, never composed into a statement, never shown to an employer and never enters a report |
| C3 | **The Academy''s role is stated honestly and kept narrow.** It does not counsel, diagnose or treat. It stops, signposts and escalates |

### C.2 What calls for this configuration

A participant — or, at Stage 4, anyone in the session — says or writes that they are thinking of harming themselves or someone else; discloses that they are being harmed or are unsafe; shows distress severe enough that continuing would be unkind; or has a medical emergency.

### C.3 Support information

Shown before every session and available throughout:

> If you are in crisis or thinking about harming yourself, call or text 9-8-8, any time, day or night. In an emergency, call 9-1-1.

Where a participant is outside Canada, the local emergency number applies. **The support information is held as configuration,** so it can be changed or localized without a code change.

### C.4 Stages 1 and 3 — no one is watching live

| # | Rule |
| --- | --- |
| C4a | **Before starting, the participant is told plainly that nobody reads responses while they are being written,** and is shown C.3. At Stage 1 this is the Annex A opening. **At Stage 3 it reads, exactly:** *Nobody reads your work while you are preparing it. If you need support at any time, call or text 9-8-8. In an emergency, call 9-1-1.* |
| C4b | **Stop is always available,** and is recorded under CX-28 |
| C4c | **The engine never reads, flags or interprets a response.** No automated detection is attempted: a deterministic engine cannot judge distress and must not pretend to |
| C4d | **When a confirmer at Stage 1, or a reviewing mentor at Stage 3, meets a disclosure,** they stop, record no determination, withhold the observation under CX-28 and CX-29, escalate to the Safety Contact **the same day**, and open a safety event record |

### C.5 Stages 2 and 4 — a mentor is present, on Google Meet

| # | Rule |
| --- | --- |
| C5a | **At any sign in C.2, the mentor stops the observation at once** with Stop for welfare (CX-30) |
| C5b | **The mentor stays with the person in the call,** shares C.3, does not counsel or probe, and **does not resume the observation** |
| C5c | **Stage 4:** the facilitator ends the whole session, thanks the co-participants and closes the call for them, and stays with the person affected. **The same care applies to a co-participant;** they are not observed, so nothing is recorded about them beyond the safety event |
| C5d | **The mentor escalates to the Safety Contact the same day** and opens a safety event record |
| C5e | **Nothing is recorded, and the mentor makes no notes of the disclosure** beyond the safety event record |

### C.6 The Safety Contact

A named person designated by the founder and recorded in configuration. **Until one is designated, the founder is the Safety Contact.**

On receiving an escalation, the Safety Contact decides whether and how to reach the participant, and records that decision. **Where a disclosure indicates an immediate risk to someone''s life, the Safety Contact calls 9-1-1.** What information may be shared with emergency services is confirmed by counsel before activation.

### C.7 The safety event record

| Records | Does not record |
| --- | --- |
| That an event occurred; its date and time; the Stage and source version; who acted; and what was done — stopped, signposted, escalated, emergency services contacted | **The content of the disclosure** |

It is kept separate from all evidence, and is visible only to the Safety Contact and the founder. Its retention follows counsel''s advice under REC-04.

### C.8 Training and review

Every mentor, confirmer and facilitator is trained in this configuration before authorization. It is reviewed by counsel before activation, and by the founder after the first ten real sessions or the first safety event, whichever comes first.

---',
      'source_version_hash', '748b17482b58f2320ba3dfbb44f7fcdfffa48c9a350f6a5c1f3a12cd647cc70b',
      'support_information', 'If you are in crisis or thinking about harming yourself, call or text 9-8-8, any time, day or night. In an emergency, call 9-1-1.',
      'support_information_hash', '7666620499250fda11fea1972b1b311d3974d10fe2bc30780f8916a4b8d949cb',
      'stage3_pre_start_wording', 'Nobody reads your work while you are preparing it. If you need support at any time, call or text 9-8-8. In an emergency, call 9-1-1.',
      'stage3_pre_start_wording_hash', 'f2c06f1931db8df979367ed23615814d305aed983b03e6fa6f8aab888194293f'));
  END IF;
END;
$load$;

-- ---------------------------------------------------------------------
-- 2. CX-10 — the four provenance slots, named, with no field renamed
--
-- Section 8.1 names three references and the run table has four columns.
-- The mapping is recorded as ROWS so that "which issued object belongs in
-- prompt_ref_version_id" is a fact the guard reads, not a rule written
-- twice. The column names are untouched (Standing Rule 4): what is added is
-- a register saying what each one holds.
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.t3a_d1_s1_provenance_slot (
  slot_column        text PRIMARY KEY,
  holds              text NOT NULL,
  issued_identifier  text,
  supplied_by        text NOT NULL,
  issued_under       text NOT NULL
);

COMMENT ON TABLE public.t3a_d1_s1_provenance_slot IS
  'CX-10. What each of the four provenance columns on t3a_d1_ai_administration_run holds, and who supplies it. No column is renamed; this names them. issued_identifier is NULL for the model reference because the delivery engine that fills it is the build''s to supply under CX-08 and does not exist yet — a null here is the honest state, and t3a_d1_s1_production_provenance refuses a real run while it stands.';

INSERT INTO public.t3a_d1_s1_provenance_slot
  (slot_column, holds, issued_identifier, supplied_by, issued_under)
VALUES
  ('model_ref_version_id',
   'The engine''s identifier, version and code hash',
   NULL,
   'The build, under CX-08',
   'T3A-D1-EXEC-CORR-006 Section 4.2, CX-10'),
  ('prompt_ref_version_id',
   'Annex A — the Stage 1 Delivery Specification',
   'T3A-S1-DELIVERY-SPEC-001',
   'T3A-D1-EXEC-CORR-006',
   'T3A-D1-EXEC-CORR-006 Section 4.2, CX-10'),
  ('admin_config_version_id',
   'Annex B — the Stage 1 Administration Configuration',
   'T3A-S1-ADMIN-CONFIG-001',
   'T3A-D1-EXEC-CORR-006',
   'T3A-D1-EXEC-CORR-006 Section 4.2, CX-10'),
  ('safety_config_version_id',
   'Annex C — the Participant Safety Configuration',
   'T3A-PARTICIPANT-SAFETY-001',
   'T3A-D1-EXEC-CORR-006',
   'T3A-D1-EXEC-CORR-006 Section 4.2, CX-10')
ON CONFLICT (slot_column) DO UPDATE SET
  holds             = EXCLUDED.holds,
  issued_identifier = EXCLUDED.issued_identifier,
  supplied_by       = EXCLUDED.supplied_by,
  issued_under      = EXCLUDED.issued_under;

ALTER TABLE public.t3a_d1_s1_provenance_slot ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS t3a_d1_s1_provenance_slot_read ON public.t3a_d1_s1_provenance_slot;
CREATE POLICY t3a_d1_s1_provenance_slot_read
  ON public.t3a_d1_s1_provenance_slot FOR SELECT TO authenticated USING (true);

-- ---------------------------------------------------------------------
-- 3. CX-12 — what a real run may cite, reported rather than inferred
--
-- "A real run then refuses only for the reasons Section 8.1 and the
-- activation gate already give — never for missing content." Three of the
-- four are now present, so the only missing content is the engine, and this
-- function says so by name instead of leaving a caller to read a NOT NULL
-- violation and guess.
-- ---------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.t3a_d1_s1_production_provenance()
RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $fn$
  WITH slot AS (
    SELECT s.slot_column, s.holds, s.issued_identifier, s.supplied_by,
           cv.content_version_id,
           cv.body ->> 'source_version_hash' AS version_hash
      FROM public.t3a_d1_s1_provenance_slot s
      LEFT JOIN public.t3a_content_object co
        ON co.identifier = s.issued_identifier
      LEFT JOIN public.t3a_d1_content_version cv
        ON cv.content_object_id = co.content_object_id AND cv.superseded_by IS NULL
  )
  SELECT jsonb_build_object(
    'slots', (SELECT jsonb_agg(jsonb_build_object(
                'slot_column', slot.slot_column,
                'holds', slot.holds,
                'issued_identifier', slot.issued_identifier,
                'supplied_by', slot.supplied_by,
                'loaded', slot.content_version_id IS NOT NULL,
                'version_id', slot.content_version_id,
                'version_hash', slot.version_hash) ORDER BY slot.slot_column)
               FROM slot),
    'all_four_present', (SELECT bool_and(slot.content_version_id IS NOT NULL) FROM slot),
    'missing', (SELECT coalesce(jsonb_agg(slot.slot_column ORDER BY slot.slot_column), '[]'::jsonb)
                  FROM slot WHERE slot.content_version_id IS NULL),
    'refusal_code', CASE WHEN (SELECT bool_and(slot.content_version_id IS NOT NULL) FROM slot)
                         THEN NULL ELSE 'S1_PRODUCTION_PROVENANCE_INCOMPLETE' END,
    'remedy', CASE WHEN (SELECT bool_and(slot.content_version_id IS NOT NULL) FROM slot)
                   THEN NULL
                   ELSE 'The delivery engine''s model reference is the build''s to supply under CX-08 '
                        'and is not built yet. Until it exists, a real Stage 1 run has no fourth '
                        'provenance object to cite.' END);
$fn$;

COMMENT ON FUNCTION public.t3a_d1_s1_production_provenance() IS
  'CX-12. Which of the four Stage 1 provenance objects a real run can cite today, and which cannot, by name. Reads the CX-10 slot register rather than restating the mapping.';

GRANT EXECUTE ON FUNCTION public.t3a_d1_s1_production_provenance() TO authenticated;

-- ---------------------------------------------------------------------
-- 4. Assert the text, from what was STORED
--
-- Recomputed from the database, not from the generator's own variables, so
-- this catches a hand-edit of the SQL above as well as a load that dropped
-- a character.
-- ---------------------------------------------------------------------

DO $verify$
DECLARE
  r       record;
  v_n     int := 0;
  v_key   text;
BEGIN
  FOR r IN
    SELECT co.identifier, cv.body
      FROM public.t3a_content_object co
      JOIN public.t3a_d1_content_version cv
        ON cv.content_object_id = co.content_object_id AND cv.superseded_by IS NULL
     WHERE co.identifier IN ('T3A-S1-DELIVERY-SPEC-001', 'T3A-S1-ADMIN-CONFIG-001',
                             'T3A-PARTICIPANT-SAFETY-001')
  LOOP
    v_n := v_n + 1;

    -- Every <key>_hash in the body must be the sha256 of <key>.
    FOR v_key IN
      SELECT k FROM jsonb_object_keys(r.body) k WHERE k LIKE '%\_hash'
    LOOP
      DECLARE
        v_subject text := left(v_key, length(v_key) - 5);
        v_stored  text := r.body ->> v_key;
        v_text    text;
      BEGIN
        -- source_version_hash names 'verbatim', not a key called 'source_version'.
        IF v_key = 'source_version_hash' THEN v_subject := 'verbatim'; END IF;
        v_text := r.body ->> v_subject;

        IF v_text IS NULL THEN
          RAISE EXCEPTION 'ANNEX_HASH_HAS_NO_SUBJECT: % carries % but no key %', r.identifier, v_key, v_subject;
        END IF;
        IF encode(sha256(convert_to(v_text, 'UTF8')), 'hex') IS DISTINCT FROM v_stored THEN
          RAISE EXCEPTION 'ANNEX_TEXT_DRIFTED: %.% does not hash to its stored %. Participant-facing wording is not paraphrased.', r.identifier, v_subject, v_key;
        END IF;
      END;
    END LOOP;
  END LOOP;

  IF v_n <> 3 THEN
    RAISE EXCEPTION 'ANNEX_LOAD_INCOMPLETE: % of the three annex objects are loaded.', v_n;
  END IF;

  RAISE NOTICE 'Annexes A, B and C loaded; every stored block hashes to itself.';
END;
$verify$;

-- ---------------------------------------------------------------------
-- 5. CX-09 — the demonstration objects are untouched, asserted
-- ---------------------------------------------------------------------

DO $cx09$
DECLARE v_n int; v_bar int;
BEGIN
  SELECT count(*) INTO v_n
    FROM public.t3a_content_object co
    JOIN public.t3a_d1_content_version cv
      ON cv.content_object_id = co.content_object_id AND cv.superseded_by IS NULL
   WHERE co.identifier LIKE 'SYNTHETIC\_TEST\_ONLY-D1-%'
     AND (cv.body ->> 'synthetic_test_only')::boolean IS TRUE;

  -- Named exactly, and named from reading pg_trigger rather than from a
  -- comment: the first draft asserted
  -- t3a_d1_ai_administration_run_synthetic_bar_trg, which I inferred from
  -- the prose in 20261061000000. The trigger is
  -- t3a_d1_ai_run_synthetic_bar_trg, so the whole migration refused to
  -- commit. That is the assertion working, and it is also AS-41 again:
  -- name the object, and read the object's name from the object.
  SELECT count(*) INTO v_bar
    FROM pg_trigger t JOIN pg_proc p ON p.oid = t.tgfoid
   WHERE NOT t.tgisinternal
     AND t.tgrelid = 'public.t3a_d1_ai_administration_run'::regclass
     AND t.tgname = 't3a_d1_ai_run_synthetic_bar_trg'
     AND p.proname = 't3a_d1_ai_run_synthetic_bar';

  IF v_n <> 4 THEN
    RAISE EXCEPTION 'CX09_DEMONSTRATION_OBJECTS_DISTURBED: % objects still marked synthetic_test_only, expected four.', v_n;
  END IF;
  IF v_bar <> 1 THEN
    RAISE EXCEPTION 'CX09_SYNTHETIC_BAR_MISSING: the trigger refusing a real run that cites demonstration provenance is not on the run table.';
  END IF;

  RAISE NOTICE 'CX-09: four demonstration objects intact and still barred from a real run.';
END;
$cx09$;

-- ---------------------------------------------------------------------
-- 6. What this leaves open
-- ---------------------------------------------------------------------

INSERT INTO public.t3a_d1_build_conflict_register
  (entry_id, opened_by, scope, classification, status, blocked_on, note)
VALUES
  ('CORR-006/CX-12/annex-c-registered-under-one-dimension',
   'CORR-006 Section 4, while loading Annex C',
   'The scope a safety configuration is registered with',
   'recorded rather than decided — the content register has no wider scope to use',
   'open',
   'Founder: confirm that one registration of T3A-PARTICIPANT-SAFETY-001 under D1 is intended to '
   || 'govern every dimension, or direct that the register carry a scope wider than a dimension.',
   'Annex C says of itself that it "governs every Stage of every dimension". Every row in '
   || 't3a_content_object carries a single dimension_id, and there is no value meaning "all". '
   || 'T3A-PARTICIPANT-SAFETY-001 is therefore registered under D1, which is where it is cited from '
   || 'today and is the only dimension that exists. '
   || 'WHY THIS IS NOT NOTHING. The obvious alternatives were both worse. Loading a copy per '
   || 'dimension would create several objects where the founder issued one, and the copies would '
   || 'drift — a safety configuration is the last content that should exist in more than one place. '
   || 'Adding an "all dimensions" sentinel to the register would change what a dimension_id means '
   || 'for every object in the schema, which is a doctrine change and the DEVELOPER JUDGMENT '
   || 'BOUNDARY reserves those. So one object, registered where it is used, and the discrepancy '
   || 'between its stated scope and its registered scope recorded here rather than papered over. '
   || 'NOTHING IS BLOCKED: D2 does not exist yet, so no Stage of any other dimension is currently '
   || 'unable to cite it.')
ON CONFLICT (entry_id) DO UPDATE SET
  opened_by = EXCLUDED.opened_by, scope = EXCLUDED.scope,
  classification = EXCLUDED.classification, status = EXCLUDED.status,
  blocked_on = EXCLUDED.blocked_on, note = EXCLUDED.note;
