-- =====================================================================
-- T3A-D1-EXEC-001 §11 — the acceptance evidence for build 7e597da
--
-- "Every test is executed and its evidence returned with the build: test
--  identifier, actual result, pass or fail, build version, date,
--  tester."
--
-- Thirty records, one per test. Nine passed, fourteen are blocked by a
-- governing input that does not exist, and seven were not executed in
-- this run and say so.
--
-- §11: "Where a test cannot pass because a governing input is missing,
-- record it as a conflict — do not resolve it by hiding a field, adding
-- free text, introducing a default, combining controls, or reducing
-- either live view." The fourteen blocked records name the missing input
-- rather than a weakened version of the test.
--
-- The seven not-executed records are the ones it would have been easiest
-- to write a reason for and call passed. They are recorded as not
-- executed because they were not executed.
--
-- This does not make the acceptance evidence complete, and
-- t3a_d1_acceptance_evidence_complete() will keep returning false and
-- naming the twenty-one tests without a pass. That is the correct state
-- and not something to work around: T3A-D1-REL-001 reads it.
-- =====================================================================

INSERT INTO public.t3a_d1_acceptance_evidence
  (test_id, outcome, actual_result, build_version, tester, conflict_note)
VALUES
  ($lit$AC-02$lit$, $lit$pass$lit$::public.t3a_d1_acceptance_outcome, $lit$t3a_d1_s2_capture_permitted(1279,800,'desktop') returned VIEWPORT_BELOW_SUPPORTED_MINIMUM with the minimum and the reported size named; (1280,800) returned permitted. The screen returns the refusal before the layout, and the region grid carries no responsive breakpoint at all (asserted by test).$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, NULL),
  ($lit$AC-03$lit$, $lit$pass$lit$::public.t3a_d1_acceptance_outcome, $lit$t3a_d1_s2_capture_permitted(1920,1080,'phone') returned STAGE_2_LIVE_CAPTURE_NOT_AVAILABLE_ON_A_PHONE. A phone is refused on device class, so a phone reporting a large viewport is refused too.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, NULL),
  ($lit$AC-07$lit$, $lit$pass$lit$::public.t3a_d1_acceptance_outcome, $lit$t3a_d1_served_questions with Q-D1-03a = corresponded served neither Q-D1-03b1 nor Q-D1-03b2 (BR-01). No child row exists, so no missing state can attach to one.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, NULL),
  ($lit$AC-09$lit$, $lit$pass$lit$::public.t3a_d1_acceptance_outcome, $lit$For SRC-D1-S2-002 with no answers: 9 served, 2 not served. Every unserved question carries a reason_code; none carries an answer row, a placeholder or a missing-state control.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, NULL),
  ($lit$AC-14$lit$, $lit$pass$lit$::public.t3a_d1_acceptance_outcome, $lit$A variance inserted at beat B3 wrote one row to t3a_d1_s2_administration_variance. The composed-statement count was unchanged and the md5 over every content version body was unchanged, so it edited no source text and no determination. The table is append-only server-side.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, NULL),
  ($lit$AC-20$lit$, $lit$pass$lit$::public.t3a_d1_acceptance_outcome, $lit$The Cockpit contains no transcript, speech, suggestion, preselection, reorder or colour-code path into a determination; no defaultChecked or defaultValue; and selections come only from the approved option set. Asserted by test.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, NULL),
  ($lit$AC-21$lit$, $lit$pass$lit$::public.t3a_d1_acceptance_outcome, $lit$No score, rank, level, readiness, trait, recommendation, evidence state, report statement, coverage meter, traffic light or progress percentage exists on the Cockpit. Asserted by test against fields and controls rather than vocabulary.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, NULL),
  ($lit$AC-22$lit$, $lit$pass$lit$::public.t3a_d1_acceptance_outcome, $lit$No combined control exists on any D1 surface: no confirm-and-proceed, save-and-advance, complete-and-continue or review-and-issue. Capture, confirmation, review and issuance are separate persisted actions, and the reviewer cannot issue the report they reviewed. Asserted by test.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, NULL),
  ($lit$AC-30$lit$, $lit$pass$lit$::public.t3a_d1_acceptance_outcome, $lit$The Cockpit references no rehearsal table, completion, frequency, selection, performance or history: zero occurrences of the term and no read of any rehearsal table.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, NULL),
  ($lit$AC-01$lit$, $lit$blocked_by_conflict$lit$::public.t3a_d1_acceptance_outcome, $lit$The six regions are built and arranged per build 057, and the layout carries no breakpoint that could reduce one. Simultaneous visibility of both LIVE VIEWS cannot be observed.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, $lit$Both live views are placeholders. The meeting workspace that supplies the media tracks has not landed, so there is no track to observe.$lit$),
  ($lit$AC-04$lit$, $lit$blocked_by_conflict$lit$::public.t3a_d1_acceptance_outcome, $lit$Pane 1 renders the loaded source body read-only, but not an ACTIVE APPROVED version, and BRIEF/READ/ASK/PAUSE/SAY distinction cannot be verified against an approved instance.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, $lit$No source is registered for serving: none of the forty holds a REC-07 approval or a source-version hash (§5.18), so no approved source instance can be rendered at a beat.$lit$),
  ($lit$AC-05$lit$, $lit$blocked_by_conflict$lit$::public.t3a_d1_acceptance_outcome, $lit$Branch and serving logic are proved at the register level, but advancing a beat against an approved source instance cannot be exercised.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, $lit$No source is registered for serving: none of the forty holds a REC-07 approval or a source-version hash (§5.18), so no approved source instance can be rendered at a beat.$lit$),
  ($lit$AC-06$lit$, $lit$blocked_by_conflict$lit$::public.t3a_d1_acceptance_outcome, $lit$The approved answer set per question is proved against the register; rendering at the correct beat of an approved instance cannot be exercised.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, $lit$No source is registered for serving: none of the forty holds a REC-07 approval or a source-version hash (§5.18), so no approved source instance can be rendered at a beat.$lit$),
  ($lit$AC-08$lit$, $lit$blocked_by_conflict$lit$::public.t3a_d1_acceptance_outcome, $lit$BR-02 and BR-03 serve the exact children at the register level. A wrong-source child or list refusing cannot be exercised without an approved instance to be wrong about.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, $lit$No source is registered for serving: none of the forty holds a REC-07 approval or a source-version hash (§5.18), so no approved source instance can be rendered at a beat.$lit$),
  ($lit$AC-12$lit$, $lit$blocked_by_conflict$lit$::public.t3a_d1_acceptance_outcome, $lit$The B2 pause instruction and the ten-to-fifteen second window are specified; recording the elapsed pause and binding a timing-dependent capture to it needs a live beat run.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, $lit$No source is registered for serving: none of the forty holds a REC-07 approval or a source-version hash (§5.18), so no approved source instance can be rendered at a beat.$lit$),
  ($lit$AC-13$lit$, $lit$blocked_by_conflict$lit$::public.t3a_d1_acceptance_outcome, $lit$Timing integrity needs recorded beat timestamps from a live run.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, $lit$No source is registered for serving: none of the forty holds a REC-07 approval or a source-version hash (§5.18), so no approved source instance can be rendered at a beat.$lit$),
  ($lit$AC-17$lit$, $lit$blocked_by_conflict$lit$::public.t3a_d1_acceptance_outcome, $lit$Refresh and recovery needs an uncommitted live session to restore.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, $lit$No source is registered for serving: none of the forty holds a REC-07 approval or a source-version hash (§5.18), so no approved source instance can be rendered at a beat.$lit$),
  ($lit$AC-23$lit$, $lit$blocked_by_conflict$lit$::public.t3a_d1_acceptance_outcome, $lit$The §3.3 rule itself is proved: 2s AVAILABLE, 3s DEGRADED, 9s DEGRADED, 10s UNAVAILABLE, ended track UNAVAILABLE immediately, restoration at 4s still UNAVAILABLE and at 5s AVAILABLE with a variance on resumption. The Cockpit reads that verdict and holds no second opinion. What cannot be executed is the rule firing against a real track.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, $lit$Both live views are placeholders. The meeting workspace that supplies the media tracks has not landed, so there is no track to observe.$lit$),
  ($lit$AC-24$lit$, $lit$blocked_by_conflict$lit$::public.t3a_d1_acceptance_outcome, $lit$No D1 surface contains any media capture, recording or upload API, and t3a_d1_consent_type records RECORDING as unavailable in D1. The live views operating without persisting media cannot be observed, because they do not yet operate. SEPARATELY FLAGGED: the legacy route /dashboard/candidate/observations/session captures microphone speech and produces AI scores per dimension. It writes to no t3a_d1 table, but it is live and participant-facing. Recorded in the report as a conflict for the founder.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, $lit$Both live views are placeholders. The meeting workspace that supplies the media tracks has not landed, so there is no track to observe.$lit$),
  ($lit$AC-26$lit$, $lit$blocked_by_conflict$lit$::public.t3a_d1_acceptance_outcome, $lit$Counting context switches across a full seven-beat session needs a session to run.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, $lit$No source is registered for serving: none of the forty holds a REC-07 approval or a source-version hash (§5.18), so no approved source instance can be rendered at a beat.$lit$),
  ($lit$AC-27$lit$, $lit$blocked_by_conflict$lit$::public.t3a_d1_acceptance_outcome, $lit$Automatic surfacing of the current beat, timing, question set and branch needs an approved instance to surface them from.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, $lit$No source is registered for serving: none of the forty holds a REC-07 approval or a source-version hash (§5.18), so no approved source instance can be rendered at a beat.$lit$),
  ($lit$AC-28$lit$, $lit$blocked_by_conflict$lit$::public.t3a_d1_acceptance_outcome, $lit$Contemporaneous capture at the beat with timestamp and context needs a live run; late capture is already identified rather than disguised at the data layer.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, $lit$No source is registered for serving: none of the forty holds a REC-07 approval or a source-version hash (§5.18), so no approved source instance can be rendered at a beat.$lit$),
  ($lit$AC-31$lit$, $lit$blocked_by_conflict$lit$::public.t3a_d1_acceptance_outcome, $lit$As AC-23. The rule is proved; the mentor view has no real track to lose.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, $lit$Both live views are placeholders. The meeting workspace that supplies the media tracks has not landed, so there is no track to observe.$lit$),
  ($lit$AC-10$lit$, $lit$not_executed$lit$::public.t3a_d1_acceptance_outcome, $lit$Not executed in this run. Commit refusal on an unresolved served item exists at the data layer and has not been exercised as an acceptance test.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, NULL),
  ($lit$AC-11$lit$, $lit$not_executed$lit$::public.t3a_d1_acceptance_outcome, $lit$Not executed in this run. The missing-state register holds eight codes, of which §5.5 permits six at commit; the workbench offers those six and treats them as field metadata, never as substantive answers. Recording that as a pass needs the test run, not the reasoning.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, NULL),
  ($lit$AC-15$lit$, $lit$not_executed$lit$::public.t3a_d1_acceptance_outcome, $lit$Not executed in this run.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, NULL),
  ($lit$AC-16$lit$, $lit$not_executed$lit$::public.t3a_d1_acceptance_outcome, $lit$Not executed in this run.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, NULL),
  ($lit$AC-18$lit$, $lit$not_executed$lit$::public.t3a_d1_acceptance_outcome, $lit$Not executed in this run.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, NULL),
  ($lit$AC-19$lit$, $lit$not_executed$lit$::public.t3a_d1_acceptance_outcome, $lit$Not executed in this run.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, NULL),
  ($lit$AC-29$lit$, $lit$not_executed$lit$::public.t3a_d1_acceptance_outcome, $lit$Not executed in this run.$lit$, $lit$7e597da$lit$, $lit$Claude Code, automated, non-production environment$lit$, NULL);
