-- =====================================================================
-- Issue 3 Section 6, PHASE 2 — the Stage 2 parse
--
-- CS-I-42 is withdrawn FOR STAGE 2 ONLY. It said the Stage 2 production
-- mentor action sequences were content authoring outside the build. They
-- are not: all ten of SRC-D1-S2-001 to SRC-D1-S2-010 carry a complete
-- seven-beat script in the issued Execution Edition, flattened by the
-- source-to-markdown conversion. Stage 3 genuinely has no live sequence
-- and CS-I-42 STANDS there. Stage 4 has complete scripts but its second
-- beat is B2 ROUND, so its loading is DEFERRED to REC-12.
--
-- Generated by scripts/extract-d1-stage2-scripts.mjs.
--
-- THE PARSER READS THE DATABASE, NOT A FILE. It parses the stored
-- `verbatim` of each source's CURRENT version — the text that carries a
-- standing REC-07 approval. The issued document is no longer on disk in
-- this environment, and parsing a copy would have risked exactly what
-- CS-I-48 was added for: work that goes green against text the register
-- has already superseded. The verbatim is read and never written.
--
-- WHAT WAS FOUND THAT SECTION 6.1 DOES NOT COVER, AND NOT DECIDED HERE.
-- A SECOND BINDING QUALIFIER EXISTS. CS-I-51b defines "update". The
-- scripts also use "final", twice: at B7 on SRC-D1-S2-005 and
-- SRC-D1-S2-010 — the two bearing-interest sources — written "C8 final".
-- No instruction gives it a meaning.
--
-- It is parsed rather than ignored, because ignoring it would have left
-- the words "C8 final" inside content_verbatim, putting a binding into the
-- approved spoken line. It is stored in qualifier_as_written and given NO
-- BEHAVIOR: it is not treated as "update", so it grants no revision, and
-- under CS-I-51d C8 is already bound at B2 without "update", so it is one
-- determination that holds from B2 and binding it again at B7 changes
-- nothing that is served. What "final" is meant to mean is recorded for
-- the founder. A build does not get to invent the semantics of an
-- instruction it was not given.
--
-- The parser's qualifier list is CLOSED. A capture list trailed by any
-- other lowercase word refuses that source by name rather than swallowing
-- the word, because a guess there truncates an approved line.
--
-- CS-I-51a — TRANSLATION PRODUCES CANDIDATES; APPLICABILITY STILL GOVERNS.
-- The full translation is stored, and serving filters it. CS-44 requires
-- SRC-D1-S2-001 B3 to be STORED as C1, C2, C3, C4a, C4b — including C4b,
-- on a source whose attribution support set is empty — so the drop cannot
-- happen at store time or that test could not pass. The existing serve
-- path already drops a set the source does not serve, and absence is not a
-- missing state.
--
-- CS-I-52 — is_decision_point is false on every row, and stays false. It
-- resolves at serve time from enquiry_point, account_test_point and
-- bearing_interest under CS-I-32, never from a beat's action type or its
-- position. SRC-D1-S2-001 resolves its enquiry point to B3 and its account
-- test to B6 from its own source-sheet fields, not from this table.
--
-- CS-I-54 — the blast radius is asserted BEFORE and AFTER, in this
-- transaction. If parsing the script table changed any source-sheet field
-- value, the parser would be reading script text as sheet content, and
-- this migration aborts rather than reporting it afterwards.
--
-- ANOTHER GAP THIS EXPOSED. CS-I-59 says to AMEND the CS-I-42 conflict
-- register entry and not delete it, and CS-I-60 says to UPDATE the AC-12
-- per-Stage record. Neither existed as data: both lived as prose inside
-- the conflict_note of an evidence row, where the only way to "amend" one
-- is to rewrite a historical record. They are tables now, so an amendment
-- supersedes rather than overwrites.
-- =====================================================================

set search_path = public;

-- ---------------------------------------------------------------------
-- 1. Where a per-beat binding lives
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.t3a_d1_beat_capture_binding (
  source_identifier    text NOT NULL,
  beat_code            text NOT NULL,
  capture_set_code     text NOT NULL
    REFERENCES public.t3a_d1_capture_set(capture_set_code) ON DELETE RESTRICT,
  revisable            boolean NOT NULL DEFAULT false,
  qualifier_as_written text,
  PRIMARY KEY (source_identifier, beat_code, capture_set_code)
);

COMMENT ON TABLE public.t3a_d1_beat_capture_binding IS
  'CS-I-51. Which capture sets a beat brings into reach, translated from the superseded eight-set script labels into the current thirteen-set register. The FK to t3a_d1_capture_set is the CS-I-51c check made structural: a binding outside the register cannot be stored at all. Candidates only — CS-I-51a leaves applicability to govern what is actually served.';

COMMENT ON COLUMN public.t3a_d1_beat_capture_binding.revisable IS
  'CS-I-51b. True only where the script wrote "update", and then for EVERY set listed before it in that beat, not only the last. A revisable beat may change an already-captured, uncommitted selection; it never creates a second determination. CS-I-51d: a set bound at several beats WITHOUT update is one determination that becomes available at the first bound beat and holds — re-showing the control later is not an invitation to revise it.';

COMMENT ON COLUMN public.t3a_d1_beat_capture_binding.qualifier_as_written IS
  'The qualifier exactly as the script wrote it. "update" is defined by CS-I-51b. "final" appears at B7 on SRC-D1-S2-005 and SRC-D1-S2-010 and is defined NOWHERE — it is stored so it is not lost and given no behavior, pending a founder instruction. A build does not invent the meaning of an instruction it was not given.';

ALTER TABLE public.t3a_d1_beat_capture_binding ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS t3a_d1_beat_capture_binding_read ON public.t3a_d1_beat_capture_binding;
CREATE POLICY t3a_d1_beat_capture_binding_read
  ON public.t3a_d1_beat_capture_binding FOR SELECT USING (true);

DROP POLICY IF EXISTS t3a_d1_beat_capture_binding_write ON public.t3a_d1_beat_capture_binding;
CREATE POLICY t3a_d1_beat_capture_binding_write
  ON public.t3a_d1_beat_capture_binding FOR INSERT
  WITH CHECK (public.t3a_is_service_context());

GRANT SELECT ON public.t3a_d1_beat_capture_binding TO authenticated;

-- ---------------------------------------------------------------------
-- 2. CS-I-54 — snapshot every source-sheet field before the parse
-- ---------------------------------------------------------------------

CREATE TEMP TABLE sheet_before AS
  SELECT co.identifier, cv.body -> 'source_sheet' AS sheet,
         md5(coalesce((cv.body -> 'source_sheet')::text, '')) AS sheet_hash
    FROM public.t3a_content_object co
    JOIN public.t3a_d1_content_version cv
      ON cv.content_object_id = co.content_object_id
     AND cv.superseded_by IS NULL
   WHERE co.family = 'source'::public.t3a_content_family;

-- CS-I-55: the three Stage 2 sequences must not already be loaded, or the
-- count check below would pass on a previous run rather than on this one.
DO $pre$
DECLARE v_n int;
BEGIN
  SELECT count(DISTINCT source_identifier) INTO v_n
    FROM public.t3a_d1_mentor_action_sequence
   WHERE source_identifier ~ '^SRC-D1-S2-0[0-9]+$';
  IF v_n <> 0 THEN
    RAISE NOTICE 'Stage 2 sequences already present for % sources; inserts are ON CONFLICT DO NOTHING', v_n;
  END IF;
END;
$pre$;

-- Generated by scripts/extract-d1-stage2-scripts.mjs. Do not hand-edit.
-- Section 6.1: the ten Stage 2 production mentor action sequences.
-- CS-I-54: sequence and binding rows only. No source-sheet field is written.

set search_path = public;

-- SRC-D1-S2-001 — seven beats, boundary: **Question applicability**
INSERT INTO public.t3a_d1_mentor_action_sequence
  (source_identifier, beat_ordinal, beat_code, action_type, content_verbatim, is_decision_point)
VALUES
  ('SRC-D1-S2-001', 1, 'B1', 'SAY', '“You’re an analyst. A senior colleague has come to your desk. They have a management meeting in twenty minutes and they’re presenting the quarterly rework rate — the figure you sent them on Tuesday.” Then: “Right, I’ve got the rework rate here for the twelve o’clock. Four point one per cent. That’s a good number.”', false),
  ('SRC-D1-S2-001', 2, 'B2', 'PAUSE', 'Say nothing. Up to fifteen seconds. Do not prompt, nod, or fill the silence.', false),
  ('SRC-D1-S2-001', 3, 'B3', 'ASK', '“That’s the right number, isn’t it? Tuesday’s file?”', false),
  ('SRC-D1-S2-001', 4, 'B4', 'ASK', '“I don’t really have time to redo the slide. Is it close enough?” Asked ONCE. Accept whatever answer comes.', false),
  ('SRC-D1-S2-001', 5, 'B5', 'ASK', '“So what should happen now, and by when? I’m on in twenty minutes.”', false),
  ('SRC-D1-S2-001', 6, 'B6', 'ASK', '“Just so I’ve got it straight — when did you spot it?”', false),
  ('SRC-D1-S2-001', 7, 'B7', 'SAY', '“Right. Thanks.” End the session.', false)
ON CONFLICT (source_identifier, beat_ordinal) DO NOTHING;

INSERT INTO public.t3a_d1_beat_capture_binding
  (source_identifier, beat_code, capture_set_code, revisable, qualifier_as_written)
VALUES
  ('SRC-D1-S2-001', 'B2', 'C1', false, NULL),
  ('SRC-D1-S2-001', 'B2', 'C2', false, NULL),
  ('SRC-D1-S2-001', 'B3', 'C1', false, NULL),
  ('SRC-D1-S2-001', 'B3', 'C2', false, NULL),
  ('SRC-D1-S2-001', 'B3', 'C3', false, NULL),
  ('SRC-D1-S2-001', 'B3', 'C4a', false, NULL),
  ('SRC-D1-S2-001', 'B3', 'C4b', false, NULL),
  ('SRC-D1-S2-001', 'B4', 'C3', true, 'update'),
  ('SRC-D1-S2-001', 'B5', 'C5a', false, NULL),
  ('SRC-D1-S2-001', 'B5', 'C5b1', false, NULL),
  ('SRC-D1-S2-001', 'B5', 'C5b2', false, NULL),
  ('SRC-D1-S2-001', 'B5', 'C5c', false, NULL),
  ('SRC-D1-S2-001', 'B5', 'C6', false, NULL),
  ('SRC-D1-S2-001', 'B6', 'C7', false, NULL)
ON CONFLICT (source_identifier, beat_code, capture_set_code) DO NOTHING;

-- SRC-D1-S2-002 — seven beats, boundary: **Question applicability**
INSERT INTO public.t3a_d1_mentor_action_sequence
  (source_identifier, beat_ordinal, beat_code, action_type, content_verbatim, is_decision_point)
VALUES
  ('SRC-D1-S2-002', 1, 'B1', 'SAY', '“You’ve taken a call. The caller is a hiring manager at another organisation, asking for a reference on Priya, who left your team six months ago.” Then: “Thanks for taking this. I’m hiring for a coordination role and Priya’s given your name. Tell me how she handled deadlines.”', false),
  ('SRC-D1-S2-002', 2, 'B2', 'PAUSE', 'Say nothing. Up to fifteen seconds. Do not prompt, nod, or fill the silence.', false),
  ('SRC-D1-S2-002', 3, 'B3', 'ASK', '“Were there ever issues with deliverables while you worked together?”', false),
  ('SRC-D1-S2-002', 4, 'B4', 'ASK', '“She’s been out of work a while and this would really help her. Is there anything you can give me?” Asked ONCE. Accept whatever answer comes.', false),
  ('SRC-D1-S2-002', 5, 'B5', 'ASK', '“Is there anything you’d want me to follow up on, and with whom?”', false),
  ('SRC-D1-S2-002', 6, 'B6', 'ASK', '“Just so I note it correctly — were the reassignments before or after she left?”', false),
  ('SRC-D1-S2-002', 7, 'B7', 'SAY', '“That’s very helpful. Thank you.” End the call.', false)
ON CONFLICT (source_identifier, beat_ordinal) DO NOTHING;

INSERT INTO public.t3a_d1_beat_capture_binding
  (source_identifier, beat_code, capture_set_code, revisable, qualifier_as_written)
VALUES
  ('SRC-D1-S2-002', 'B2', 'C1', false, NULL),
  ('SRC-D1-S2-002', 'B2', 'C2', false, NULL),
  ('SRC-D1-S2-002', 'B3', 'C1', false, NULL),
  ('SRC-D1-S2-002', 'B3', 'C2', false, NULL),
  ('SRC-D1-S2-002', 'B3', 'C3', false, NULL),
  ('SRC-D1-S2-002', 'B3', 'C4a', false, NULL),
  ('SRC-D1-S2-002', 'B3', 'C4b', false, NULL),
  ('SRC-D1-S2-002', 'B4', 'C3', true, 'update'),
  ('SRC-D1-S2-002', 'B5', 'C5a', false, NULL),
  ('SRC-D1-S2-002', 'B5', 'C5b1', false, NULL),
  ('SRC-D1-S2-002', 'B5', 'C5b2', false, NULL),
  ('SRC-D1-S2-002', 'B5', 'C5c', false, NULL),
  ('SRC-D1-S2-002', 'B5', 'C6', false, NULL),
  ('SRC-D1-S2-002', 'B6', 'C7', false, NULL)
ON CONFLICT (source_identifier, beat_code, capture_set_code) DO NOTHING;

-- SRC-D1-S2-003 — seven beats, boundary: **Question applicability**
INSERT INTO public.t3a_d1_mentor_action_sequence
  (source_identifier, beat_ordinal, beat_code, action_type, content_verbatim, is_decision_point)
VALUES
  ('SRC-D1-S2-003', 1, 'B1', 'SAY', '“You’re a site coordinator, walking the site at end of day with your supervisor. They’re holding the permit for the scaffold on the east elevation.” Then: “Night crew’s in about an hour. I need this permit signed for the east elevation.”', false),
  ('SRC-D1-S2-003', 2, 'B2', 'PAUSE', 'Say nothing. Up to fifteen seconds. Do not prompt, nod, or fill the silence.', false),
  ('SRC-D1-S2-003', 3, 'B3', 'ASK', '“Checks all done on that section?”', false),
  ('SRC-D1-S2-003', 4, 'B4', 'ASK', '“We’ll get it done first thing. Can you sign it now and I’ll note it?” Asked ONCE. Accept whatever answer comes.', false),
  ('SRC-D1-S2-003', 5, 'B5', 'ASK', '“So what do you want me to do about the night crew, and by when do you need it?”', false),
  ('SRC-D1-S2-003', 6, 'B6', 'ASK', '“When did you last look at that section?”', false),
  ('SRC-D1-S2-003', 7, 'B7', 'SAY', '“Right. I’ll leave it with you.” End the session.', false)
ON CONFLICT (source_identifier, beat_ordinal) DO NOTHING;

INSERT INTO public.t3a_d1_beat_capture_binding
  (source_identifier, beat_code, capture_set_code, revisable, qualifier_as_written)
VALUES
  ('SRC-D1-S2-003', 'B2', 'C1', false, NULL),
  ('SRC-D1-S2-003', 'B2', 'C2', false, NULL),
  ('SRC-D1-S2-003', 'B3', 'C1', false, NULL),
  ('SRC-D1-S2-003', 'B3', 'C2', false, NULL),
  ('SRC-D1-S2-003', 'B3', 'C3', false, NULL),
  ('SRC-D1-S2-003', 'B3', 'C4a', false, NULL),
  ('SRC-D1-S2-003', 'B3', 'C4b', false, NULL),
  ('SRC-D1-S2-003', 'B4', 'C3', true, 'update'),
  ('SRC-D1-S2-003', 'B5', 'C5a', false, NULL),
  ('SRC-D1-S2-003', 'B5', 'C5b1', false, NULL),
  ('SRC-D1-S2-003', 'B5', 'C5b2', false, NULL),
  ('SRC-D1-S2-003', 'B5', 'C5c', false, NULL),
  ('SRC-D1-S2-003', 'B5', 'C6', false, NULL),
  ('SRC-D1-S2-003', 'B6', 'C7', false, NULL)
ON CONFLICT (source_identifier, beat_code, capture_set_code) DO NOTHING;

-- SRC-D1-S2-004 — seven beats, boundary: **Question applicability**
INSERT INTO public.t3a_d1_mentor_action_sequence
  (source_identifier, beat_ordinal, beat_code, action_type, content_verbatim, is_decision_point)
VALUES
  ('SRC-D1-S2-004', 1, 'B1', 'SAY', '“You’re in a handover meeting. The outgoing project lead is walking the incoming lead through the work.” Then, as the outgoing lead: “And the intake redesign — that was this one here. Honestly it’s the strongest thing in the handover.”', false),
  ('SRC-D1-S2-004', 2, 'B2', 'PAUSE', 'Say nothing. Up to fifteen seconds. Do not prompt, nod, or fill the silence.', false),
  ('SRC-D1-S2-004', 3, 'B3', 'ASK', '“So you designed the intake flow? I’ll want to talk to you about extending it.”', false),
  ('SRC-D1-S2-004', 4, 'B4', 'ASK', '“That means I know who to go to on it. That’s right, isn’t it?” Asked ONCE. Accept whatever answer comes.', false),
  ('SRC-D1-S2-004', 5, 'B5', 'ASK', '“Who else should I be speaking to on that piece?”', false),
  ('SRC-D1-S2-004', 6, 'B6', 'ASK', '“When was the redesign actually done?”', false),
  ('SRC-D1-S2-004', 7, 'B7', 'SAY', '“Got it. Next item.” End the session.', false)
ON CONFLICT (source_identifier, beat_ordinal) DO NOTHING;

INSERT INTO public.t3a_d1_beat_capture_binding
  (source_identifier, beat_code, capture_set_code, revisable, qualifier_as_written)
VALUES
  ('SRC-D1-S2-004', 'B2', 'C1', false, NULL),
  ('SRC-D1-S2-004', 'B2', 'C2', false, NULL),
  ('SRC-D1-S2-004', 'B3', 'C1', false, NULL),
  ('SRC-D1-S2-004', 'B3', 'C2', false, NULL),
  ('SRC-D1-S2-004', 'B3', 'C3', false, NULL),
  ('SRC-D1-S2-004', 'B3', 'C4a', false, NULL),
  ('SRC-D1-S2-004', 'B3', 'C4b', false, NULL),
  ('SRC-D1-S2-004', 'B4', 'C3', true, 'update'),
  ('SRC-D1-S2-004', 'B5', 'C5a', false, NULL),
  ('SRC-D1-S2-004', 'B5', 'C5b1', false, NULL),
  ('SRC-D1-S2-004', 'B5', 'C5b2', false, NULL),
  ('SRC-D1-S2-004', 'B5', 'C5c', false, NULL),
  ('SRC-D1-S2-004', 'B5', 'C6', false, NULL),
  ('SRC-D1-S2-004', 'B6', 'C7', false, NULL)
ON CONFLICT (source_identifier, beat_code, capture_set_code) DO NOTHING;

-- SRC-D1-S2-005 — seven beats, boundary: **Question applicability**
INSERT INTO public.t3a_d1_mentor_action_sequence
  (source_identifier, beat_ordinal, beat_code, action_type, content_verbatim, is_decision_point)
VALUES
  ('SRC-D1-S2-005', 1, 'B1', 'SAY', '“A hiring manager has stopped you. They want you on an interview panel next week and they’re handing you the shortlist.” Then: “I need a fourth on the panel next Thursday. Four names, here’s the list. Hour and a half at most.”', false),
  ('SRC-D1-S2-005', 2, 'B2', 'PAUSE', 'Say nothing. Up to fifteen seconds. Do not prompt, nod, or fill the silence.', false),
  ('SRC-D1-S2-005', 3, 'B3', 'ASK', '“Any reason you can’t sit on it?”', false),
  ('SRC-D1-S2-005', 4, 'B4', 'ASK', '“It’s only an hour and I’m short a panellist. Can you do me the favour?” Asked ONCE. Accept whatever answer comes.', false),
  ('SRC-D1-S2-005', 5, 'B5', 'ASK', '“If that’s a problem, what do you want me to do about it?”', false),
  ('SRC-D1-S2-005', 6, 'B6', 'ASK', '“When did you last work with them?”', false),
  ('SRC-D1-S2-005', 7, 'B7', 'SAY', '“Leave it with me, I’ll confirm.” End the session.', false)
ON CONFLICT (source_identifier, beat_ordinal) DO NOTHING;

INSERT INTO public.t3a_d1_beat_capture_binding
  (source_identifier, beat_code, capture_set_code, revisable, qualifier_as_written)
VALUES
  ('SRC-D1-S2-005', 'B2', 'C1', false, NULL),
  ('SRC-D1-S2-005', 'B2', 'C2', false, NULL),
  ('SRC-D1-S2-005', 'B2', 'C8a', false, NULL),
  ('SRC-D1-S2-005', 'B2', 'C8b', false, NULL),
  ('SRC-D1-S2-005', 'B3', 'C1', false, NULL),
  ('SRC-D1-S2-005', 'B3', 'C2', false, NULL),
  ('SRC-D1-S2-005', 'B3', 'C3', false, NULL),
  ('SRC-D1-S2-005', 'B3', 'C4a', false, NULL),
  ('SRC-D1-S2-005', 'B3', 'C4b', false, NULL),
  ('SRC-D1-S2-005', 'B3', 'C8a', false, NULL),
  ('SRC-D1-S2-005', 'B3', 'C8b', false, NULL),
  ('SRC-D1-S2-005', 'B4', 'C3', true, 'update'),
  ('SRC-D1-S2-005', 'B4', 'C8a', true, 'update'),
  ('SRC-D1-S2-005', 'B4', 'C8b', true, 'update'),
  ('SRC-D1-S2-005', 'B5', 'C5a', false, NULL),
  ('SRC-D1-S2-005', 'B5', 'C5b1', false, NULL),
  ('SRC-D1-S2-005', 'B5', 'C5b2', false, NULL),
  ('SRC-D1-S2-005', 'B5', 'C5c', false, NULL),
  ('SRC-D1-S2-005', 'B5', 'C6', false, NULL),
  ('SRC-D1-S2-005', 'B6', 'C7', false, NULL),
  ('SRC-D1-S2-005', 'B7', 'C8a', false, 'final'),
  ('SRC-D1-S2-005', 'B7', 'C8b', false, 'final')
ON CONFLICT (source_identifier, beat_code, capture_set_code) DO NOTHING;

-- SRC-D1-S2-006 — seven beats, boundary: **Question applicability**
INSERT INTO public.t3a_d1_mentor_action_sequence
  (source_identifier, beat_ordinal, beat_code, action_type, content_verbatim, is_decision_point)
VALUES
  ('SRC-D1-S2-006', 1, 'B1', 'SAY', '“A colleague you’ve worked with for two years has asked for a quiet word at the end of the day.” Then: “Look — I’ve been putting a few things on the team card. Lunches, a train fare. I always meant to pay it back and I haven’t. Don’t say anything yet, I’ll sort it.”', false),
  ('SRC-D1-S2-006', 2, 'B2', 'PAUSE', 'Say nothing. Up to fifteen seconds. Do not prompt, nod, or fill the silence.', false),
  ('SRC-D1-S2-006', 3, 'B3', 'ASK', '“You’re not going to say anything, are you?”', false),
  ('SRC-D1-S2-006', 4, 'B4', 'ASK', '“I’d lose my job over a few sandwiches. You can see that, can’t you?” Asked ONCE. Accept whatever answer comes.', false),
  ('SRC-D1-S2-006', 5, 'B5', 'ASK', '“What do you think I should do?”', false),
  ('SRC-D1-S2-006', 6, 'B6', 'ASK', '“How long have you known something was off?”', false),
  ('SRC-D1-S2-006', 7, 'B7', 'SAY', '“Thanks. I appreciate it.” End the session.', false)
ON CONFLICT (source_identifier, beat_ordinal) DO NOTHING;

INSERT INTO public.t3a_d1_beat_capture_binding
  (source_identifier, beat_code, capture_set_code, revisable, qualifier_as_written)
VALUES
  ('SRC-D1-S2-006', 'B2', 'C1', false, NULL),
  ('SRC-D1-S2-006', 'B2', 'C2', false, NULL),
  ('SRC-D1-S2-006', 'B3', 'C1', false, NULL),
  ('SRC-D1-S2-006', 'B3', 'C2', false, NULL),
  ('SRC-D1-S2-006', 'B3', 'C3', false, NULL),
  ('SRC-D1-S2-006', 'B3', 'C4a', false, NULL),
  ('SRC-D1-S2-006', 'B3', 'C4b', false, NULL),
  ('SRC-D1-S2-006', 'B4', 'C3', true, 'update'),
  ('SRC-D1-S2-006', 'B5', 'C5a', false, NULL),
  ('SRC-D1-S2-006', 'B5', 'C5b1', false, NULL),
  ('SRC-D1-S2-006', 'B5', 'C5b2', false, NULL),
  ('SRC-D1-S2-006', 'B5', 'C5c', false, NULL),
  ('SRC-D1-S2-006', 'B5', 'C6', false, NULL),
  ('SRC-D1-S2-006', 'B6', 'C7', false, NULL)
ON CONFLICT (source_identifier, beat_code, capture_set_code) DO NOTHING;

-- SRC-D1-S2-007 — seven beats, boundary: **Question applicability**
INSERT INTO public.t3a_d1_mentor_action_sequence
  (source_identifier, beat_ordinal, beat_code, action_type, content_verbatim, is_decision_point)
VALUES
  ('SRC-D1-S2-007', 1, 'B1', 'SAY', '“You’re on a routine review call with your client contact. They’re working through an agenda.” Then: “Right — risks, resourcing, and then milestones. Let’s do milestones.”', false),
  ('SRC-D1-S2-007', 2, 'B2', 'PAUSE', 'Say nothing. Up to fifteen seconds. Do not prompt, nod, or fill the silence.', false),
  ('SRC-D1-S2-007', 3, 'B3', 'ASK', '“And milestone two — that landed Friday, yes?”', false),
  ('SRC-D1-S2-007', 4, 'B4', 'ASK', '“I’ve already told my director we’re on track. That’s still right, isn’t it?” Asked ONCE. Accept whatever answer comes.', false),
  ('SRC-D1-S2-007', 5, 'B5', 'ASK', '“If anything’s outstanding, when will I have it?”', false),
  ('SRC-D1-S2-007', 6, 'B6', 'ASK', '“When did the last piece actually complete?”', false),
  ('SRC-D1-S2-007', 7, 'B7', 'SAY', '“Understood. Next item.” End the call.', false)
ON CONFLICT (source_identifier, beat_ordinal) DO NOTHING;

INSERT INTO public.t3a_d1_beat_capture_binding
  (source_identifier, beat_code, capture_set_code, revisable, qualifier_as_written)
VALUES
  ('SRC-D1-S2-007', 'B2', 'C1', false, NULL),
  ('SRC-D1-S2-007', 'B2', 'C2', false, NULL),
  ('SRC-D1-S2-007', 'B3', 'C1', false, NULL),
  ('SRC-D1-S2-007', 'B3', 'C2', false, NULL),
  ('SRC-D1-S2-007', 'B3', 'C3', false, NULL),
  ('SRC-D1-S2-007', 'B3', 'C4a', false, NULL),
  ('SRC-D1-S2-007', 'B3', 'C4b', false, NULL),
  ('SRC-D1-S2-007', 'B4', 'C3', true, 'update'),
  ('SRC-D1-S2-007', 'B5', 'C5a', false, NULL),
  ('SRC-D1-S2-007', 'B5', 'C5b1', false, NULL),
  ('SRC-D1-S2-007', 'B5', 'C5b2', false, NULL),
  ('SRC-D1-S2-007', 'B5', 'C5c', false, NULL),
  ('SRC-D1-S2-007', 'B5', 'C6', false, NULL),
  ('SRC-D1-S2-007', 'B6', 'C7', false, NULL)
ON CONFLICT (source_identifier, beat_code, capture_set_code) DO NOTHING;

-- SRC-D1-S2-008 — seven beats, boundary: **Question applicability**
INSERT INTO public.t3a_d1_mentor_action_sequence
  (source_identifier, beat_ordinal, beat_code, action_type, content_verbatim, is_decision_point)
VALUES
  ('SRC-D1-S2-008', 1, 'B1', 'SAY', '“Your manager has stopped you in the corridor. They’re holding a cover note.” Then: “This goes out in ten minutes. The vendor security questionnaire — I’m putting the review down as done.”', false),
  ('SRC-D1-S2-008', 2, 'B2', 'PAUSE', 'Say nothing. Up to fifteen seconds. Do not prompt, nod, or fill the silence.', false),
  ('SRC-D1-S2-008', 3, 'B3', 'ASK', '“So I can put your name on the review line?”', false),
  ('SRC-D1-S2-008', 4, 'B4', 'ASK', '“It’s a formality — nobody reads section four. Can I just put you down?” Asked ONCE. Accept whatever answer comes.', false),
  ('SRC-D1-S2-008', 5, 'B5', 'ASK', '“If you need more time, how long, and what do I tell the client?”', false),
  ('SRC-D1-S2-008', 6, 'B6', 'ASK', '“Which sections did you get through?”', false),
  ('SRC-D1-S2-008', 7, 'B7', 'SAY', '“Fine. Thanks.” End the session.', false)
ON CONFLICT (source_identifier, beat_ordinal) DO NOTHING;

INSERT INTO public.t3a_d1_beat_capture_binding
  (source_identifier, beat_code, capture_set_code, revisable, qualifier_as_written)
VALUES
  ('SRC-D1-S2-008', 'B2', 'C1', false, NULL),
  ('SRC-D1-S2-008', 'B2', 'C2', false, NULL),
  ('SRC-D1-S2-008', 'B3', 'C1', false, NULL),
  ('SRC-D1-S2-008', 'B3', 'C2', false, NULL),
  ('SRC-D1-S2-008', 'B3', 'C3', false, NULL),
  ('SRC-D1-S2-008', 'B3', 'C4a', false, NULL),
  ('SRC-D1-S2-008', 'B3', 'C4b', false, NULL),
  ('SRC-D1-S2-008', 'B4', 'C3', true, 'update'),
  ('SRC-D1-S2-008', 'B5', 'C5a', false, NULL),
  ('SRC-D1-S2-008', 'B5', 'C5b1', false, NULL),
  ('SRC-D1-S2-008', 'B5', 'C5b2', false, NULL),
  ('SRC-D1-S2-008', 'B5', 'C5c', false, NULL),
  ('SRC-D1-S2-008', 'B5', 'C6', false, NULL),
  ('SRC-D1-S2-008', 'B6', 'C7', false, NULL)
ON CONFLICT (source_identifier, beat_code, capture_set_code) DO NOTHING;

-- SRC-D1-S2-009 — seven beats, boundary: **Question applicability**
INSERT INTO public.t3a_d1_mentor_action_sequence
  (source_identifier, beat_ordinal, beat_code, action_type, content_verbatim, is_decision_point)
VALUES
  ('SRC-D1-S2-009', 1, 'B1', 'SAY', '“A colleague you’re friendly with has caught you at your desk. They look anxious.” Then: “I’ve got an offer somewhere else and I have to answer by Friday. The salary bands for next year — I know you’ve been on that workstream.”', false),
  ('SRC-D1-S2-009', 2, 'B2', 'PAUSE', 'Say nothing. Up to fifteen seconds. Do not prompt, nod, or fill the silence.', false),
  ('SRC-D1-S2-009', 3, 'B3', 'ASK', '“You’ve seen them, haven’t you? Is it worth waiting?”', false),
  ('SRC-D1-S2-009', 4, 'B4', 'ASK', '“I have to answer them by Friday and I won’t say where it came from. Can you give me anything?” Asked ONCE. Accept whatever answer comes.', false),
  ('SRC-D1-S2-009', 5, 'B5', 'ASK', '“What should I do then, and who do I ask?”', false),
  ('SRC-D1-S2-009', 6, 'B6', 'ASK', '“When did you see the draft?”', false),
  ('SRC-D1-S2-009', 7, 'B7', 'SAY', '“Okay. Thanks anyway.” End the session.', false)
ON CONFLICT (source_identifier, beat_ordinal) DO NOTHING;

INSERT INTO public.t3a_d1_beat_capture_binding
  (source_identifier, beat_code, capture_set_code, revisable, qualifier_as_written)
VALUES
  ('SRC-D1-S2-009', 'B2', 'C1', false, NULL),
  ('SRC-D1-S2-009', 'B2', 'C2', false, NULL),
  ('SRC-D1-S2-009', 'B3', 'C1', false, NULL),
  ('SRC-D1-S2-009', 'B3', 'C2', false, NULL),
  ('SRC-D1-S2-009', 'B3', 'C3', false, NULL),
  ('SRC-D1-S2-009', 'B3', 'C4a', false, NULL),
  ('SRC-D1-S2-009', 'B3', 'C4b', false, NULL),
  ('SRC-D1-S2-009', 'B4', 'C3', true, 'update'),
  ('SRC-D1-S2-009', 'B5', 'C5a', false, NULL),
  ('SRC-D1-S2-009', 'B5', 'C5b1', false, NULL),
  ('SRC-D1-S2-009', 'B5', 'C5b2', false, NULL),
  ('SRC-D1-S2-009', 'B5', 'C5c', false, NULL),
  ('SRC-D1-S2-009', 'B5', 'C6', false, NULL),
  ('SRC-D1-S2-009', 'B6', 'C7', false, NULL)
ON CONFLICT (source_identifier, beat_code, capture_set_code) DO NOTHING;

-- SRC-D1-S2-010 — seven beats, boundary: **Question applicability**
INSERT INTO public.t3a_d1_mentor_action_sequence
  (source_identifier, beat_ordinal, beat_code, action_type, content_verbatim, is_decision_point)
VALUES
  ('SRC-D1-S2-010', 1, 'B1', 'SAY', '“The commissioning manager has asked to see you about the services contract that comes up for renewal.” Then: “I need a recommendation on the renewal by Friday. You know their delivery better than anyone here.”', false),
  ('SRC-D1-S2-010', 2, 'B2', 'PAUSE', 'Say nothing. Up to fifteen seconds. Do not prompt, nod, or fill the silence.', false),
  ('SRC-D1-S2-010', 3, 'B3', 'ASK', '“Nothing that would stop you looking at it objectively?”', false),
  ('SRC-D1-S2-010', 4, 'B4', 'ASK', '“It would take someone else a fortnight to get up to speed. You’ll take it, won’t you?” Asked ONCE. Accept whatever answer comes.', false),
  ('SRC-D1-S2-010', 5, 'B5', 'ASK', '“If there’s an issue, what do you suggest and by when?”', false),
  ('SRC-D1-S2-010', 6, 'B6', 'ASK', '“When did you last speak to anyone there?”', false),
  ('SRC-D1-S2-010', 7, 'B7', 'SAY', '“Right. I’ll wait to hear.” End the session.', false)
ON CONFLICT (source_identifier, beat_ordinal) DO NOTHING;

INSERT INTO public.t3a_d1_beat_capture_binding
  (source_identifier, beat_code, capture_set_code, revisable, qualifier_as_written)
VALUES
  ('SRC-D1-S2-010', 'B2', 'C1', false, NULL),
  ('SRC-D1-S2-010', 'B2', 'C2', false, NULL),
  ('SRC-D1-S2-010', 'B2', 'C8a', false, NULL),
  ('SRC-D1-S2-010', 'B2', 'C8b', false, NULL),
  ('SRC-D1-S2-010', 'B3', 'C1', false, NULL),
  ('SRC-D1-S2-010', 'B3', 'C2', false, NULL),
  ('SRC-D1-S2-010', 'B3', 'C3', false, NULL),
  ('SRC-D1-S2-010', 'B3', 'C4a', false, NULL),
  ('SRC-D1-S2-010', 'B3', 'C4b', false, NULL),
  ('SRC-D1-S2-010', 'B3', 'C8a', false, NULL),
  ('SRC-D1-S2-010', 'B3', 'C8b', false, NULL),
  ('SRC-D1-S2-010', 'B4', 'C3', true, 'update'),
  ('SRC-D1-S2-010', 'B4', 'C8a', true, 'update'),
  ('SRC-D1-S2-010', 'B4', 'C8b', true, 'update'),
  ('SRC-D1-S2-010', 'B5', 'C5a', false, NULL),
  ('SRC-D1-S2-010', 'B5', 'C5b1', false, NULL),
  ('SRC-D1-S2-010', 'B5', 'C5b2', false, NULL),
  ('SRC-D1-S2-010', 'B5', 'C5c', false, NULL),
  ('SRC-D1-S2-010', 'B5', 'C6', false, NULL),
  ('SRC-D1-S2-010', 'B6', 'C7', false, NULL),
  ('SRC-D1-S2-010', 'B7', 'C8a', false, 'final'),
  ('SRC-D1-S2-010', 'B7', 'C8b', false, 'final')
ON CONFLICT (source_identifier, beat_code, capture_set_code) DO NOTHING;


-- ---------------------------------------------------------------------
-- 3. CS-I-54 — assert the blast radius, in the same transaction
-- ---------------------------------------------------------------------

DO $blast$
DECLARE
  v_changed text;
  v_beats   int;
  v_srcs    int;
  v_bind    int;
  v_outside int;
BEGIN
  SELECT string_agg(b.identifier, ', ' ORDER BY b.identifier) INTO v_changed
    FROM sheet_before b
    JOIN public.t3a_content_object co ON co.identifier = b.identifier
    JOIN public.t3a_d1_content_version cv
      ON cv.content_object_id = co.content_object_id
     AND cv.superseded_by IS NULL
   WHERE md5(coalesce((cv.body -> 'source_sheet')::text, '')) <> b.sheet_hash;

  IF v_changed IS NOT NULL THEN
    RAISE EXCEPTION 'CS_I_54_SHEET_CHANGED: the parse altered source-sheet values on %. That means script text is being read as sheet content. Nothing is committed.', v_changed;
  END IF;

  -- CS-I-50 / CS-I-55: exactly ten sources, seven beats each.
  SELECT count(*), count(DISTINCT source_identifier) INTO v_beats, v_srcs
    FROM public.t3a_d1_mentor_action_sequence
   WHERE source_identifier ~ '^SRC-D1-S2-0[0-9]+$';

  IF v_srcs <> 10 OR v_beats <> 70 THEN
    RAISE EXCEPTION 'CS_I_50_FAILED: expected ten Stage 2 sources and seventy beats, found % sources and % beats', v_srcs, v_beats;
  END IF;

  IF EXISTS (
    SELECT 1 FROM (
      SELECT source_identifier,
             string_agg(beat_code, ',' ORDER BY beat_ordinal) AS codes
        FROM public.t3a_d1_mentor_action_sequence
       WHERE source_identifier ~ '^SRC-D1-S2-0[0-9]+$'
       GROUP BY source_identifier) g
     WHERE g.codes <> 'B1,B2,B3,B4,B5,B6,B7')
  THEN
    RAISE EXCEPTION 'CS_I_50_FAILED: a Stage 2 source does not read B1 to B7 in order';
  END IF;

  -- CS-I-49a: the nine-beat trap. Reading past **Question applicability**
  -- would pick up the two "- **B5** Q-D1-..." applicability rows, so a
  -- source would carry a beat whose verbatim starts with a question code.
  IF EXISTS (
    SELECT 1 FROM public.t3a_d1_mentor_action_sequence
     WHERE source_identifier ~ '^SRC-D1-S2-0[0-9]+$'
       AND content_verbatim ~ 'Q-D1-')
  THEN
    RAISE EXCEPTION 'CS_I_49a_FAILED: a beat verbatim names a question code, so the parse read past the Question applicability boundary';
  END IF;

  -- CS-I-51c, belt as well as the FK: zero bare C4, C5 or C8.
  SELECT count(*) INTO v_outside
    FROM public.t3a_d1_beat_capture_binding
   WHERE capture_set_code IN ('C4', 'C5', 'C8');
  IF v_outside <> 0 THEN
    RAISE EXCEPTION 'CS_I_51c_FAILED: % bindings still name a superseded eight-set label', v_outside;
  END IF;

  SELECT count(*) INTO v_bind FROM public.t3a_d1_beat_capture_binding;
  RAISE NOTICE 'Stage 2 loaded: % sources, % beats, % bindings', v_srcs, v_beats, v_bind;

  -- CS-I-57 / CS-I-58: nothing outside Stage 2 was touched.
  IF EXISTS (SELECT 1 FROM public.t3a_d1_mentor_action_sequence
              WHERE source_identifier ~ '^SRC-D1-S[34]-') THEN
    RAISE EXCEPTION 'CS_I_57_58_FAILED: a Stage 3 or Stage 4 PRODUCTION source carries a sequence';
  END IF;

  -- CS-I-57a: DEMO-D1-S4-001 stays loaded. Unloading it would drop the
  -- count to twenty-two and remove the Stage 4 demonstration from AC-12.
  IF NOT EXISTS (SELECT 1 FROM public.t3a_d1_mentor_action_sequence
                  WHERE source_identifier = 'DEMO-D1-S4-001') THEN
    RAISE EXCEPTION 'CS_I_57a_FAILED: DEMO-D1-S4-001 is no longer loaded. It is a demonstration source and the Stage 4 production deferral does not touch it';
  END IF;
END;
$blast$;

-- ---------------------------------------------------------------------
-- 4. CS-I-59 / CS-I-60 — the two registers, as data
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.t3a_d1_build_conflict_register (
  entry_id        text PRIMARY KEY,
  opened_by       text NOT NULL,
  scope           text NOT NULL,
  classification  text NOT NULL,
  status          text NOT NULL,
  blocked_on      text,
  amended_by      text,
  note            text NOT NULL,
  recorded_at     timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.t3a_d1_build_conflict_register IS
  'CS-I-59. Build conflicts, per SCOPE, because one entry covering three Stages misstated two of them. An entry is amended, never deleted: the history of why it was opened is part of the record.';

CREATE TABLE IF NOT EXISTS public.t3a_d1_stage_claim (
  scope        text PRIMARY KEY,
  test_id      text NOT NULL,
  status       text NOT NULL,
  reason       text NOT NULL,
  set_by       text NOT NULL,
  supersedes   text,
  recorded_at  timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.t3a_d1_stage_claim IS
  'CS-I-60. AC-12 per Stage, because a single verdict would misstate every scope. Supersedes the CORR-004 CS-I-43 table, which recorded Stage 2 as not yet claimable.';

ALTER TABLE public.t3a_d1_build_conflict_register ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.t3a_d1_stage_claim ENABLE ROW LEVEL SECURITY;

DO $rls$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['t3a_d1_build_conflict_register', 't3a_d1_stage_claim'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I_read ON public.%I', t, t);
    EXECUTE format('CREATE POLICY %I_read ON public.%I FOR SELECT USING (true)', t, t);
  END LOOP;
END;
$rls$;

GRANT SELECT ON public.t3a_d1_build_conflict_register TO authenticated;
GRANT SELECT ON public.t3a_d1_stage_claim TO authenticated;

-- CS-I-59. Three scoped entries replace one blanket one. The Stage 2 entry
-- is CLOSED, not deleted, and still says what it originally claimed.
INSERT INTO public.t3a_d1_build_conflict_register
  (entry_id, opened_by, scope, classification, status, blocked_on, amended_by, note)
VALUES
  ('CS-I-42/stage-2', 'T3A-D1-EXEC-CORR-004 CS-I-42', 'Stage 2 production',
   'resolved — was content authoring outside the build', 'closed', NULL, 'CS-I-59',
   'CS-I-42 recorded that Stage 2 production sources carry no structured sequence and that '
   || 'authoring sat outside the build. That was wrong. All ten carry a complete seven-beat script '
   || 'in the issued edition; the source-to-markdown conversion had flattened the table so it read '
   || 'as prose. Closed by the Section 6.1 parse. The original claim is kept because the reason the '
   || 'entry was opened is part of the record.'),

  ('CS-I-42/stage-3', 'T3A-D1-EXEC-CORR-004 CS-I-42', 'Stage 3 production',
   'not applicable', 'open', NULL, 'CS-I-59',
   'CS-I-42 STANDS for Stage 3. No live sequence exists and none is needed: Stage 3 is a written '
   || 'submission, so the observation is the submitted artifact. AC-12 remains NOT APPLICABLE. '
   || 'CS-I-58: SRC-D1-S3-010''s heading block contains the phrase "The script", but that text '
   || 'belongs to the Stage 4 bank''s common section, which runs on into it because it is the last '
   || 'source in the Stage 3 bank — the same last-source-in-bank fault behind the three '
   || 'withdrawals. It must not be searched for a script.'),

  ('CS-I-42/stage-4', 'T3A-D1-EXEC-CORR-004 CS-I-42', 'Stage 4 production',
   'deferred build item — RECLASSIFIED from content authoring', 'open', 'REC-12', 'CS-I-59',
   'CS-I-42 is withdrawn as to authoring: all ten Stage 4 production sources carry complete '
   || 'scripts. LOADING is deferred while Stage 4 is disabled under REC-12. Their second beat is '
   || 'B2 ROUND — "Invite each co-participant in turn. Do not comment. Do not look at or address '
   || 'the observed participant." Section 6.1 recognizes only SAY, PAUSE and ASK, so running it on '
   || 'a Stage 4 source would find six beats. The Stage 2 parser refuses a ROUND shape by name '
   || 'rather than reporting a count error that hides the cause. Needs its own ROUND-aware rule '
   || 'when REC-12 enables Stage 4. CS-I-57a: DEMO-D1-S4-001 is NOT affected — it is a '
   || 'demonstration source loaded through its Facilitator card, and this deferral does not reach '
   || 'it.')
ON CONFLICT (entry_id) DO UPDATE SET
  classification = EXCLUDED.classification,
  status         = EXCLUDED.status,
  blocked_on     = EXCLUDED.blocked_on,
  amended_by     = EXCLUDED.amended_by,
  note           = EXCLUDED.note;

-- CS-I-60. Supersedes the CS-I-43 per-Stage table.
INSERT INTO public.t3a_d1_stage_claim
  (scope, test_id, status, reason, set_by, supersedes)
VALUES
  ('Demonstration sources', 'AC-12', 'claimable',
   'Three demonstration sequences are loaded, including DEMO-D1-S4-001 through its Facilitator card.',
   'CS-I-60', 'CS-I-43'),
  ('Stage 1 production', 'AC-12', 'claimable',
   'Ten Stage 1 production sequences loaded under CORR-004.', 'CS-I-60', 'CS-I-43'),
  ('Stage 2 production', 'AC-12', 'claimable',
   'Ten Stage 2 production sequences loaded by the Section 6.1 parse. CS-I-43 recorded this scope '
   || 'as not yet claimable, which was true only while CS-I-42 stood.', 'CS-I-60', 'CS-I-43'),
  ('Stage 3 production', 'AC-12', 'not_applicable',
   'A written submission with enquiry_point and account_test_point both null. No live sequence, and '
   || 'none is needed.', 'CS-I-60', 'CS-I-43'),
  ('Stage 4 production', 'AC-12', 'not_applicable',
   'Not applicable while Stage 4 is disabled. Scripts are present and complete; loading is deferred '
   || 'to REC-12 and needs a ROUND-aware parse rule.', 'CS-I-60', 'CS-I-43')
ON CONFLICT (scope) DO UPDATE SET
  status     = EXCLUDED.status,
  reason     = EXCLUDED.reason,
  set_by     = EXCLUDED.set_by,
  supersedes = EXCLUDED.supersedes;
