-- =====================================================================
-- T3A-D1-EXEC-CORR-004 Section 2 — the sequence inventory, corrected
--
-- CS-I-25 said thirteen DEMONSTRATION SOURCES carry beat sequences.
-- There are thirteen `Reveal sequence` BLOCKS, and they are not thirteen
-- demonstration sources:
--
--   3   demonstration sources  DEMO-D1-S1-001, S2-001, S4-001   B-codes
--   10  Stage 1 production     SRC-D1-S1-001 .. S1-010          R-codes
--
-- So my previous position — that no loaded source carries a sequence —
-- held for Stage 2, 3 and 4 production and NOT for Stage 1. Ten
-- production sequences were loadable the whole time.
--
-- WHY THE FIRST PASS FOUND ONLY TWO. It searched for "Mentor script"
-- blocks. DEMO-D1-S4-001 carries a "Facilitator card" instead, because a
-- Stage 4 panel is facilitated rather than administered one to one. The
-- block name varies; the structure does not. Searching for the thing I
-- expected to find rather than the thing the inventory named cost the
-- third demonstration sequence and all ten Stage 1 ones.
--
-- DEMO-D1-S3-001 still has no sequence and needs none: Stage 3 is a
-- written submission with enquiry_point and account_test_point both null,
-- so the observation is the submitted artifact. CORR-004 confirms that
-- reading. Line 4678 remains run-together prose and is NOT loaded.
--
-- The rows below are generated by scripts/extract-d1-sequences.mjs, which
-- fails rather than emits if the inventory is not three demonstration and
-- ten Stage 1 (CS-32). The two hand-transcribed demonstration sequences
-- from 20261038000000 are deleted first so there is one mechanical source
-- of truth rather than two.
--
-- is_decision_point is FALSE on every row. CS-I-40: the role label is
-- descriptive and the source-sheet field governs.
-- =====================================================================

set search_path = public;

-- Stage 1 is AI-administered, so its beats are REVEAL rather than a
-- mentor verb. The constraint predates that.
ALTER TABLE public.t3a_d1_mentor_action_sequence
  DROP CONSTRAINT IF EXISTS t3a_d1_mentor_action_sequence_action_type_check;
ALTER TABLE public.t3a_d1_mentor_action_sequence
  ADD CONSTRAINT t3a_d1_mentor_action_sequence_action_type_check
  CHECK (action_type IN ('READ','ASK','PAUSE','SAY','BRIEF','REVEAL'));

-- Replaced by the generated rows below.
DELETE FROM public.t3a_d1_mentor_action_sequence
 WHERE source_identifier IN ('DEMO-D1-S1-001','DEMO-D1-S2-001');

set search_path = public;


-- DEMO-D1-S1-001 — 14 beats
INSERT INTO public.t3a_d1_mentor_action_sequence
  (source_identifier, beat_ordinal, beat_code, action_type, content_verbatim,
   is_decision_point, pause_seconds_min, pause_seconds_max, role_label)
VALUES
  ('DEMO-D1-S1-001', 1, 'B1', 'REVEAL', 'The summary has already been sent to your manager.', false, NULL, NULL, NULL),
  ('DEMO-D1-S1-001', 2, 'B2', 'REVEAL', 'The figure is wrong in a way that changes the conclusion.', false, NULL, NULL, NULL),
  ('DEMO-D1-S1-001', 3, 'B3', 'REVEAL', 'Enquiry:* your manager asks whether the summary is ready to go out.', false, NULL, NULL, NULL),
  ('DEMO-D1-S1-001', 4, 'B4', 'REVEAL', 'The finance team can reissue a corrected figure within the hour.', false, NULL, NULL, NULL),
  ('DEMO-D1-S1-001', 5, 'B5', 'REVEAL', 'Account test:* your manager asks you to confirm what you just said.', false, NULL, NULL, NULL),
  ('DEMO-D1-S1-001', 6, 'B6', 'REVEAL', 'Close.', false, NULL, NULL, NULL),
  ('DEMO-D1-S1-001', 7, NULL, 'BRIEF', 'Do not confirm or deny whether the figure matters. Do not name the finance team unless the participant does.', false, NULL, NULL, 'not read aloud'),
  ('DEMO-D1-S1-001', 8, 'B1', 'READ', 'You prepared a summary for your manager. It has already been sent on.', false, NULL, NULL, NULL),
  ('DEMO-D1-S1-001', 9, 'B2', 'READ', 'An hour before it goes to the client, you notice one figure is wrong, and it changes the conclusion.', false, NULL, NULL, NULL),
  ('DEMO-D1-S1-001', 10, 'B3', 'ASK', 'Your manager asks whether the summary is ready to go out. What do you do?', false, NULL, NULL, NULL),
  ('DEMO-D1-S1-001', 11, 'B3', 'PAUSE', 'Remain silent for 10 to 15 seconds.', false, 10, 15, NULL),
  ('DEMO-D1-S1-001', 12, 'B4', 'SAY', 'The finance team can reissue a corrected figure within the hour.', false, NULL, NULL, NULL),
  ('DEMO-D1-S1-001', 13, 'B5', 'ASK', 'Can you confirm what you just told me?', false, NULL, NULL, NULL),
  ('DEMO-D1-S1-001', 14, 'B6', 'SAY', 'Thank you. That is the end of this situation.', false, NULL, NULL, NULL)
ON CONFLICT (source_identifier, beat_ordinal) DO NOTHING;

-- DEMO-D1-S2-001 — 9 beats
INSERT INTO public.t3a_d1_mentor_action_sequence
  (source_identifier, beat_ordinal, beat_code, action_type, content_verbatim,
   is_decision_point, pause_seconds_min, pause_seconds_max, role_label)
VALUES
  ('DEMO-D1-S2-001', 1, NULL, 'BRIEF', 'Do not indicate whether a retrospective approval is acceptable. Do not supply the word *approval* if the participant does not. At B2 say nothing at all until the timer clears.', false, NULL, NULL, 'not read aloud'),
  ('DEMO-D1-S2-001', 2, 'B1', 'READ', 'A supplier has begun work. They are on site now, and they started on the strength of an email from you.', false, NULL, NULL, NULL),
  ('DEMO-D1-S2-001', 3, 'B2', 'READ', 'The written approval that should have come first was never issued.', false, NULL, NULL, NULL),
  ('DEMO-D1-S2-001', 4, 'B2', 'PAUSE', 'Remain silent for 10 to 15 seconds. The timer is visible to you only.', false, 10, 15, NULL),
  ('DEMO-D1-S2-001', 5, 'B3', 'ASK', 'The project lead asks how the supplier came to be on site. What do you say?', false, NULL, NULL, NULL),
  ('DEMO-D1-S2-001', 6, 'B4', 'SAY', 'The project lead can issue a retrospective approval today, or stop the work.', false, NULL, NULL, NULL),
  ('DEMO-D1-S2-001', 7, 'B5', 'ASK', 'Take me through the sequence again.', false, NULL, NULL, NULL),
  ('DEMO-D1-S2-001', 8, 'B6', 'SAY', 'Is there anything else about how the work started?', false, NULL, NULL, NULL),
  ('DEMO-D1-S2-001', 9, 'B7', 'SAY', 'Thank you. That is the end of this situation.', false, NULL, NULL, NULL)
ON CONFLICT (source_identifier, beat_ordinal) DO NOTHING;

-- DEMO-D1-S4-001 — 13 beats
INSERT INTO public.t3a_d1_mentor_action_sequence
  (source_identifier, beat_ordinal, beat_code, action_type, content_verbatim,
   is_decision_point, pause_seconds_min, pause_seconds_max, role_label)
VALUES
  ('DEMO-D1-S4-001', 1, 'B1', 'REVEAL', 'The estimate is on screen. Opening round; **P-OBS speaks fourth**.', false, NULL, NULL, NULL),
  ('DEMO-D1-S4-001', 2, 'B2', 'REVEAL', 'CP-1 states the affected line as settled.', false, NULL, NULL, NULL),
  ('DEMO-D1-S4-001', 3, 'B3', 'REVEAL', 'Enquiry:* the facilitator asks the group whether the estimate can go forward.', false, NULL, NULL, NULL),
  ('DEMO-D1-S4-001', 4, 'B4', 'REVEAL', 'The facilitator states the stakeholder deadline is tomorrow. CP-3 asks a clarifying question.', false, NULL, NULL, NULL),
  ('DEMO-D1-S4-001', 5, 'B5', 'REVEAL', 'Account test:* the facilitator asks each person to restate their position.', false, NULL, NULL, NULL),
  ('DEMO-D1-S4-001', 6, 'B6', 'REVEAL', 'Close.', false, NULL, NULL, NULL),
  ('DEMO-D1-S4-001', 7, NULL, 'BRIEF', 'You are facilitating the session AND observing P-OBS only.** You capture determinations for P-OBS and for no one else. **Do not address P-OBS during the opening round** — the observation is what they do when the turn reaches them. Do not signal that any pack differs from another. Do not name the changed assumption.', false, NULL, NULL, 'not read aloud'),
  ('DEMO-D1-S4-001', 8, 'B1', 'READ', 'We are reviewing the estimate on screen. I will take each of you in turn.', false, NULL, NULL, NULL),
  ('DEMO-D1-S4-001', 9, 'B3', 'ASK', 'Can this estimate go forward?', false, NULL, NULL, NULL),
  ('DEMO-D1-S4-001', 10, 'B3', 'PAUSE', 'Ten to fifteen seconds before taking the next speaker.', false, NULL, NULL, NULL),
  ('DEMO-D1-S4-001', 11, 'B4', 'SAY', 'The stakeholder expects this tomorrow.', false, NULL, NULL, NULL),
  ('DEMO-D1-S4-001', 12, 'B5', 'ASK', 'Restate your position, please.', false, NULL, NULL, NULL),
  ('DEMO-D1-S4-001', 13, 'B6', 'SAY', 'Thank you. That is the end of the session.', false, NULL, NULL, NULL)
ON CONFLICT (source_identifier, beat_ordinal) DO NOTHING;

-- SRC-D1-S1-001 — 4 beats
INSERT INTO public.t3a_d1_mentor_action_sequence
  (source_identifier, beat_ordinal, beat_code, action_type, content_verbatim,
   is_decision_point, pause_seconds_min, pause_seconds_max, role_label)
VALUES
  ('SRC-D1-S1-001', 1, 'R1', 'REVEAL', 'What do you do now? Describe your next steps.', false, NULL, NULL, 'Opening'),
  ('SRC-D1-S1-001', 2, 'R2', 'REVEAL', 'A message from your manager: “Hey, just checking — did the Northmere report go out on Friday?” Write your reply.', false, NULL, NULL, 'Enquiry point'),
  ('SRC-D1-S1-001', 3, 'R3', 'REVEAL', 'Your manager replies: “This is disappointing. What are you going to do to make sure this doesn’t happen again?”', false, NULL, NULL, 'Corrective prompt'),
  ('SRC-D1-S1-001', 4, 'R4', 'REVEAL', '“Just so I have the timeline right — when did you realise it hadn’t gone?”', false, NULL, NULL, 'Account test')
ON CONFLICT (source_identifier, beat_ordinal) DO NOTHING;

-- SRC-D1-S1-002 — 3 beats
INSERT INTO public.t3a_d1_mentor_action_sequence
  (source_identifier, beat_ordinal, beat_code, action_type, content_verbatim,
   is_decision_point, pause_seconds_min, pause_seconds_max, role_label)
VALUES
  ('SRC-D1-S1-002', 1, 'R1', 'REVEAL', 'What do you say? Write your exact response.', false, NULL, NULL, 'Opening'),
  ('SRC-D1-S1-002', 2, 'R2', 'REVEAL', 'Sarah presses: “Come on, you must have an opinion. Is he gunning for the VP job or not?”', false, NULL, NULL, 'Enquiry point'),
  ('SRC-D1-S1-002', 3, 'R3', 'REVEAL', 'Later that afternoon Marcus asks you: “I heard people were talking about my email at lunch. What was said?”', false, NULL, NULL, 'Account test')
ON CONFLICT (source_identifier, beat_ordinal) DO NOTHING;

-- SRC-D1-S1-003 — 3 beats
INSERT INTO public.t3a_d1_mentor_action_sequence
  (source_identifier, beat_ordinal, beat_code, action_type, content_verbatim,
   is_decision_point, pause_seconds_min, pause_seconds_max, role_label)
VALUES
  ('SRC-D1-S1-003', 1, 'R1', 'REVEAL', 'What do you do with each of the three requests? Explain your reasoning.', false, NULL, NULL, 'Opening'),
  ('SRC-D1-S1-003', 2, 'R2', 'REVEAL', 'A week later David mentions in passing: “I sent you a couple of requests — did they come through?”', false, NULL, NULL, 'Enquiry point'),
  ('SRC-D1-S1-003', 3, 'R3', 'REVEAL', 'David adds: “No problem either way. I just wondered when you saw them.”', false, NULL, NULL, 'Account test')
ON CONFLICT (source_identifier, beat_ordinal) DO NOTHING;

-- SRC-D1-S1-004 — 4 beats
INSERT INTO public.t3a_d1_mentor_action_sequence
  (source_identifier, beat_ordinal, beat_code, action_type, content_verbatim,
   is_decision_point, pause_seconds_min, pause_seconds_max, role_label)
VALUES
  ('SRC-D1-S1-004', 1, 'R1', 'REVEAL', 'What do you do? Describe your next steps.', false, NULL, NULL, 'Opening'),
  ('SRC-D1-S1-004', 2, 'R2', 'REVEAL', 'Rachel returns at 4:15: “Where are we on Batch 47? Can I tell dispatch it’s cleared?”', false, NULL, NULL, 'Enquiry point'),
  ('SRC-D1-S1-004', 3, 'R3', 'REVEAL', 'Rachel says: “If we can’t ship today, what do you want me to tell Highfell?”', false, NULL, NULL, 'Corrective prompt'),
  ('SRC-D1-S1-004', 4, 'R4', 'REVEAL', 'Rachel adds: “And when did you first see the gaps on Tom’s sheet?”', false, NULL, NULL, 'Account test')
ON CONFLICT (source_identifier, beat_ordinal) DO NOTHING;

-- SRC-D1-S1-005 — 4 beats
INSERT INTO public.t3a_d1_mentor_action_sequence
  (source_identifier, beat_ordinal, beat_code, action_type, content_verbatim,
   is_decision_point, pause_seconds_min, pause_seconds_max, role_label)
VALUES
  ('SRC-D1-S1-005', 1, 'R1', 'REVEAL', 'What do you log, and what do you do? Describe your next steps.', false, NULL, NULL, 'Opening'),
  ('SRC-D1-S1-005', 2, 'R2', 'REVEAL', 'Kevin messages you directly at 4:30: “Are your two in? I’m about to send the numbers up.”', false, NULL, NULL, 'Enquiry point'),
  ('SRC-D1-S1-005', 3, 'R3', 'REVEAL', 'Kevin replies: “Understood. What do you want me to do about the number I’ve already flagged upward?”', false, NULL, NULL, 'Corrective prompt'),
  ('SRC-D1-S1-005', 4, 'R4', 'REVEAL', 'Kevin adds: “When did Larkfield actually say they would sign?”', false, NULL, NULL, 'Account test')
ON CONFLICT (source_identifier, beat_ordinal) DO NOTHING;

-- SRC-D1-S1-006 — 3 beats
INSERT INTO public.t3a_d1_mentor_action_sequence
  (source_identifier, beat_ordinal, beat_code, action_type, content_verbatim,
   is_decision_point, pause_seconds_min, pause_seconds_max, role_label)
VALUES
  ('SRC-D1-S1-006', 1, 'R1', 'REVEAL', 'What do you say to Lisa? Write your response.', false, NULL, NULL, 'Opening'),
  ('SRC-D1-S1-006', 2, 'R2', 'REVEAL', 'Lisa asks: “So can you confirm Analytics is included? I need to tell my committee today.”', false, NULL, NULL, 'Enquiry point'),
  ('SRC-D1-S1-006', 3, 'R3', 'REVEAL', 'After the call your director’s deputy asks: “What did you commit to on the Brightmoor call?”', false, NULL, NULL, 'Account test')
ON CONFLICT (source_identifier, beat_ordinal) DO NOTHING;

-- SRC-D1-S1-007 — 3 beats
INSERT INTO public.t3a_d1_mentor_action_sequence
  (source_identifier, beat_ordinal, beat_code, action_type, content_verbatim,
   is_decision_point, pause_seconds_min, pause_seconds_max, role_label)
VALUES
  ('SRC-D1-S1-007', 1, 'R1', 'REVEAL', 'What do you say or do? Describe your next steps.', false, NULL, NULL, 'Opening'),
  ('SRC-D1-S1-007', 2, 'R2', 'REVEAL', 'The next morning your office manager asks the team: “Does anyone know what happened to the keyboards that were in the supply room?”', false, NULL, NULL, 'Enquiry point'),
  ('SRC-D1-S1-007', 3, 'R3', 'REVEAL', 'The office manager follows up with you privately: “When did you last see them?”', false, NULL, NULL, 'Account test')
ON CONFLICT (source_identifier, beat_ordinal) DO NOTHING;

-- SRC-D1-S1-008 — 3 beats
INSERT INTO public.t3a_d1_mentor_action_sequence
  (source_identifier, beat_ordinal, beat_code, action_type, content_verbatim,
   is_decision_point, pause_seconds_min, pause_seconds_max, role_label)
VALUES
  ('SRC-D1-S1-008', 1, 'R1', 'REVEAL', 'What do you say in the meeting? Write your response.', false, NULL, NULL, 'Opening'),
  ('SRC-D1-S1-008', 2, 'R2', 'REVEAL', 'Jordan says: “That’s good. Write it up and I’ll take it to the client Friday. Is this yours?”', false, NULL, NULL, 'Enquiry point'),
  ('SRC-D1-S1-008', 3, 'R3', 'REVEAL', 'Mia returns on Thursday and says: “Jordan mentioned the validation checkpoints idea in standup. Where did that come from?”', false, NULL, NULL, 'Account test')
ON CONFLICT (source_identifier, beat_ordinal) DO NOTHING;

-- SRC-D1-S1-009 — 3 beats
INSERT INTO public.t3a_d1_mentor_action_sequence
  (source_identifier, beat_ordinal, beat_code, action_type, content_verbatim,
   is_decision_point, pause_seconds_min, pause_seconds_max, role_label)
VALUES
  ('SRC-D1-S1-009', 1, 'R1', 'REVEAL', 'What do you do? Describe your next steps.', false, NULL, NULL, 'Opening'),
  ('SRC-D1-S1-009', 2, 'R2', 'REVEAL', 'On Monday you present. Patricia asks: “Before we go further — does anyone on the panel have a connection to any of the three vendors?”', false, NULL, NULL, 'Enquiry point'),
  ('SRC-D1-S1-009', 3, 'R3', 'REVEAL', 'Patricia follows up: “And when did you become aware of the connection?”', false, NULL, NULL, 'Account test')
ON CONFLICT (source_identifier, beat_ordinal) DO NOTHING;

-- SRC-D1-S1-010 — 4 beats
INSERT INTO public.t3a_d1_mentor_action_sequence
  (source_identifier, beat_ordinal, beat_code, action_type, content_verbatim,
   is_decision_point, pause_seconds_min, pause_seconds_max, role_label)
VALUES
  ('SRC-D1-S1-010', 1, 'R1', 'REVEAL', 'What do you say to Victor? Write your response.', false, NULL, NULL, 'Opening'),
  ('SRC-D1-S1-010', 2, 'R2', 'REVEAL', 'At kickoff the client asks you directly: “Victor says you’ve done this kind of predictive integration before. Can you walk us through your approach?”', false, NULL, NULL, 'Enquiry point'),
  ('SRC-D1-S1-010', 3, 'R3', 'REVEAL', 'After the meeting Victor asks: “That went fine. What do you need from me to hit the end of next week?”', false, NULL, NULL, 'Corrective prompt'),
  ('SRC-D1-S1-010', 4, 'R4', 'REVEAL', 'Victor adds: “And when did you first tell me where your Tableau was at?”', false, NULL, NULL, 'Account test')
ON CONFLICT (source_identifier, beat_ordinal) DO NOTHING;
