-- =====================================================================
-- CORR-006 Section 4, CX-15 — Section 5.16's corrected text (Annex E)
--
-- GENERATED BY scripts/generate_corr006_s516.py. DO NOT HAND-EDIT.
--
-- WHAT CX-15 SAYS: "Replace the two sentences of Section 5.16 set out in
-- Annex E... Render the corrected text; the old sentences must no longer
-- render anywhere."
--
-- WHAT MEASURING FOUND, AND IT CHANGES WHAT "REPLACE" CAN MEAN HERE.
--
-- The retired sentences render NOWHERE. Searched before writing anything:
--
--     the phrase "artificial intelligence"   0 occurrences in src/,
--                                            supabase/migrations/ and in
--                                            every loaded content version
--     the string "5.16"                      0 occurrences in either
--     T3A-D1-EXEC-001 Section 5.16           not on disk and never loaded
--
-- So there is no participant notice to edit. The Section 5.16 wording that
-- tells every participant how a Stage is administered was never built, and
-- "the old sentences must no longer render anywhere" is TRUE TODAY BECAUSE
-- NOTHING RENDERS AT ALL. That is not the same as having replaced them, and
-- reporting CX-15 as "replaced" would be a false statement about
-- participant-facing text.
--
-- WHAT IS DONE INSTEAD, which is the durable half of the instruction:
--
--   1. The corrected text loads as issued content, so when the notice is
--      built there is one approved wording for it to render and no reason
--      for anyone to retype the old one from T3A-D1-EXEC-001.
--   2. Both retired sentences are recorded as RETIRED, with their hashes,
--      and a guard refuses to store any participant notice containing
--      either of them. "Must no longer render anywhere" then survives the
--      notice being built later by someone reading the superseded document.
--
-- Internal identifiers containing "AI" are NOT renamed (CX-15, and Standing
-- Rule 4): t3a_d1_ai_administration_run and its columns are untouched.
-- =====================================================================

set search_path = public;

-- ---------------------------------------------------------------------
-- 1. The retired sentences, as rows, so the guard has something to read
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.t3a_retired_participant_sentence (
  sentence_hash   text PRIMARY KEY,
  retired_text    text NOT NULL,
  replaced_by     text NOT NULL,
  retired_under   text NOT NULL,
  why             text NOT NULL
);

COMMENT ON TABLE public.t3a_retired_participant_sentence IS
  'CX-15. Participant-facing sentences that must no longer render anywhere, with what replaced them. Held as rows so the refusal reads a register rather than matching a pattern, and so a later instrument can retire another sentence without a code change. Keyed by the sha256 of the retired text.';

INSERT INTO public.t3a_retired_participant_sentence
  (sentence_hash, retired_text, replaced_by, retired_under, why)
VALUES
  ('7d759908007b3637b50bd048e66a152db886bac72505e745cf9e8510ca30c55c',
   'Some are administered using artificial intelligence.',
   'Some are presented to you on screen by an automated system.',
   'T3A-D1-EXEC-CORR-006 Annex E, CX-15',
   'Stage 1 is administered by a deterministic delivery engine and no generative model is used (CORR-006 Section 4.1), so the sentence told every participant something untrue about how they were being assessed.')
ON CONFLICT (sentence_hash) DO UPDATE SET
  retired_text = EXCLUDED.retired_text, replaced_by = EXCLUDED.replaced_by,
  retired_under = EXCLUDED.retired_under, why = EXCLUDED.why;

INSERT INTO public.t3a_retired_participant_sentence
  (sentence_hash, retired_text, replaced_by, retired_under, why)
VALUES
  ('4509d29e2419316807001f043c6833433534062464f392db35cc4eae89619379',
   'Where artificial intelligence is used, it presents the situation and organizes what happened. An authorized person is accountable for what enters your record. Artificial intelligence does not decide what your record says, does not issue your report, and does not decide a correction.',
   'Where an automated system is used, it shows you the situation in fixed stages, exactly as written, and keeps your responses exactly as you typed them. It does not write, change or judge anything, and nobody reads your responses while you are typing them. An authorized person reads them afterwards and is accountable for what enters your record. The automated system does not decide what your record says, does not issue your report, and does not decide a correction.',
   'T3A-D1-EXEC-CORR-006 Annex E, CX-15',
   'Stage 1 is administered by a deterministic delivery engine and no generative model is used (CORR-006 Section 4.1), so the sentence told every participant something untrue about how they were being assessed.')
ON CONFLICT (sentence_hash) DO UPDATE SET
  retired_text = EXCLUDED.retired_text, replaced_by = EXCLUDED.replaced_by,
  retired_under = EXCLUDED.retired_under, why = EXCLUDED.why;

ALTER TABLE public.t3a_retired_participant_sentence ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS t3a_retired_participant_sentence_read ON public.t3a_retired_participant_sentence;
CREATE POLICY t3a_retired_participant_sentence_read
  ON public.t3a_retired_participant_sentence FOR SELECT TO authenticated USING (true);

-- ---------------------------------------------------------------------
-- 2. The corrected text, as issued content
--
-- Two judgment calls here, both recorded in the register rather than
-- presented as the founder's.
--
--   The IDENTIFIER is the build's: the instrument names Annexes A, B and C
--   and does not name Annex E, and content is registered by identifier.
--
--   The FAMILY is 'configuration'. t3a_content_family has no
--   participant_notice value, and adding one would define a new class of
--   content in the schema's vocabulary — a doctrine act, which the
--   DEVELOPER JUDGMENT BOUNDARY reserves. Annex C is the precedent: the
--   Participant Safety Configuration is a configuration and carries the
--   crisis line a participant reads.
-- ---------------------------------------------------------------------

DO $load$
DECLARE v_obj uuid;
BEGIN
  SELECT content_object_id INTO v_obj FROM public.t3a_content_object
   WHERE identifier = 'T3A-D1-S516-PARTICIPANT-NOTICE-001';

  IF v_obj IS NULL THEN
    INSERT INTO public.t3a_content_object (identifier, family, title, dimension_id)
    VALUES ('T3A-D1-S516-PARTICIPANT-NOTICE-001',
            -- 'configuration', because t3a_content_family has no
            -- participant_notice value and adding one would define a new
            -- CLASS of content in the schema's vocabulary. Annex C is
            -- precedent: the Participant Safety Configuration is a
            -- configuration and carries the crisis line a participant reads.
            'configuration'::public.t3a_content_family,
            'Section 5.16, corrected text', 'D1')
    RETURNING content_object_id INTO v_obj;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.t3a_d1_content_version
                  WHERE content_object_id = v_obj AND superseded_by IS NULL) THEN
    INSERT INTO public.t3a_d1_content_version (content_object_id, version_no, body)
    VALUES (v_obj, 1, jsonb_build_object(
      'source_identifier', 'T3A-D1-S516-PARTICIPANT-NOTICE-001',
      'title', 'Section 5.16, corrected text',
      'issued_under', 'T3A-D1-EXEC-CORR-006 Annex E',
      'amends', 'T3A-D1-EXEC-001 Section 5.16 — two sentences; everything else in Section 5.16 is unchanged',
      'verbatim', 'Some are presented to you on screen by an automated system.

Where an automated system is used, it shows you the situation in fixed stages, exactly as written, and keeps your responses exactly as you typed them. It does not write, change or judge anything, and nobody reads your responses while you are typing them. An authorized person reads them afterwards and is accountable for what enters your record. The automated system does not decide what your record says, does not issue your report, and does not decide a correction.',
      'source_version_hash', 'b58a248fe9d2f8dd0c5d20871b3d3d5742f780e60e9859f2bb187a99d37601b9',
      'sentences', jsonb_build_array(
        jsonb_build_object('replaces', 'Some are administered using artificial intelligence.', 'replaces_hash', '7d759908007b3637b50bd048e66a152db886bac72505e745cf9e8510ca30c55c', 'text', 'Some are presented to you on screen by an automated system.', 'text_hash', '83d55d01797bbae3b3075244f2ff99c80545ce843774a1e6c537868f565f388e'),
        jsonb_build_object('replaces', 'Where artificial intelligence is used, it presents the situation and organizes what happened. An authorized person is accountable for what enters your record. Artificial intelligence does not decide what your record says, does not issue your report, and does not decide a correction.', 'replaces_hash', '4509d29e2419316807001f043c6833433534062464f392db35cc4eae89619379', 'text', 'Where an automated system is used, it shows you the situation in fixed stages, exactly as written, and keeps your responses exactly as you typed them. It does not write, change or judge anything, and nobody reads your responses while you are typing them. An authorized person reads them afterwards and is accountable for what enters your record. The automated system does not decide what your record says, does not issue your report, and does not decide a correction.', 'text_hash', '7d11334a837759d0cff7b795c82030306c983d7cab1ce5c60a5b03e51ab410eb'))));
  END IF;
END;
$load$;

-- ---------------------------------------------------------------------
-- 3. The refusal, so "no longer render anywhere" survives the notice being
--    built later from the superseded document
-- ---------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.t3a_participant_notice_carries_no_retired_sentence()
RETURNS trigger LANGUAGE plpgsql AS $fn$
DECLARE
  v_hit text;
BEGIN
  -- SCOPED TO EVERY CONTENT VERSION, deliberately, and this is the most
  -- restrictive of the readings available.
  --
  -- The narrower guard would apply only to a participant-facing family. But
  -- there is no such family, and a body flag the author has to remember to
  -- set is a guard that misses exactly the case it exists for — someone
  -- rebuilding the notice from the superseded T3A-D1-EXEC-001.
  --
  -- A blanket guard is safe here because it was MEASURED to be: zero loaded
  -- content versions contain either retired sentence today, so nothing
  -- already stored becomes unwritable. The cost is that a governance
  -- document QUOTING a retired sentence in order to retire it could not be
  -- loaded as content. CORR-006 is such a document and is not loaded as
  -- content, so nothing is blocked now; if that day comes, the exemption is
  -- a governance decision and belongs in an instrument rather than in a
  -- flag a build invents in advance.
  SELECT s.retired_text INTO v_hit
    FROM public.t3a_retired_participant_sentence s
   WHERE position(s.retired_text in coalesce(NEW.body ->> 'verbatim', '')) > 0
   LIMIT 1;

  IF v_hit IS NOT NULL THEN
    RAISE EXCEPTION 'PARTICIPANT_NOTICE_CARRIES_RETIRED_SENTENCE: the text contains "%" which was retired under CORR-006 Annex E. Use the replacement recorded beside it in t3a_retired_participant_sentence.', v_hit
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$fn$;

COMMENT ON FUNCTION public.t3a_participant_notice_carries_no_retired_sentence() IS
  'CX-15. Refuses ANY content version containing a retired participant sentence, by name, reading t3a_retired_participant_sentence. Blanket rather than scoped to a family because no participant-facing family exists and a body flag would be forgotten by exactly the author this guards against. Measured safe: zero loaded versions contain either sentence. A governance document quoting a retired sentence in order to retire it would be refused; CORR-006 is not loaded as content, and exempting one is a governance decision for an instrument, not a flag a build invents in advance.';

DROP TRIGGER IF EXISTS t3a_participant_notice_retired_sentence_trg
  ON public.t3a_d1_content_version;
CREATE TRIGGER t3a_participant_notice_retired_sentence_trg
  BEFORE INSERT OR UPDATE ON public.t3a_d1_content_version
  FOR EACH ROW EXECUTE FUNCTION public.t3a_participant_notice_carries_no_retired_sentence();

-- ---------------------------------------------------------------------
-- 4. Assert, from what was stored
-- ---------------------------------------------------------------------

DO $verify$
DECLARE
  v_n       int;
  v_body    jsonb;
  v_stored  text;
  s         jsonb;
BEGIN
  SELECT count(*) INTO v_n FROM public.t3a_retired_participant_sentence;
  IF v_n <> 2 THEN
    RAISE EXCEPTION 'CX15_WRONG_COUNT: % retired sentences, and Annex E replaces exactly two.', v_n;
  END IF;

  -- Each retired row's key must be the hash of its own text.
  IF EXISTS (SELECT 1 FROM public.t3a_retired_participant_sentence s
              WHERE encode(sha256(convert_to(s.retired_text, 'UTF8')), 'hex') <> s.sentence_hash) THEN
    RAISE EXCEPTION 'CX15_RETIRED_TEXT_DRIFTED: a retired sentence does not hash to its own key.';
  END IF;

  SELECT cv.body INTO v_body
    FROM public.t3a_content_object co
    JOIN public.t3a_d1_content_version cv
      ON cv.content_object_id = co.content_object_id AND cv.superseded_by IS NULL
   WHERE co.identifier = 'T3A-D1-S516-PARTICIPANT-NOTICE-001';

  IF v_body IS NULL THEN
    RAISE EXCEPTION 'CX15_NOTICE_NOT_LOADED: the corrected Section 5.16 text is not loaded.';
  END IF;

  v_stored := v_body ->> 'verbatim';
  IF encode(sha256(convert_to(v_stored, 'UTF8')), 'hex') IS DISTINCT FROM (v_body ->> 'source_version_hash') THEN
    RAISE EXCEPTION 'CX15_NOTICE_DRIFTED: the stored corrected text does not hash to its stored hash.';
  END IF;

  FOR s IN SELECT x FROM jsonb_array_elements(v_body -> 'sentences') x LOOP
    IF encode(sha256(convert_to(s ->> 'text', 'UTF8')), 'hex') IS DISTINCT FROM (s ->> 'text_hash') THEN
      RAISE EXCEPTION 'CX15_SENTENCE_DRIFTED: a corrected sentence does not hash to its stored hash.';
    END IF;
    -- The corrected wording must not itself contain what it replaces.
    IF position((s ->> 'replaces') in (s ->> 'text')) > 0 THEN
      RAISE EXCEPTION 'CX15_REPLACEMENT_CONTAINS_WHAT_IT_REPLACES.';
    END IF;
  END LOOP;

  -- And the corrected notice really did load, which means the trigger above
  -- did not refuse it — the negative control for the guard.
  RAISE NOTICE 'CX-15: two sentences retired with their hashes, the corrected notice loaded and self-consistent, and the guard admitted it.';
END;
$verify$;

-- ---------------------------------------------------------------------
-- 5. What is recorded rather than claimed
-- ---------------------------------------------------------------------

INSERT INTO public.t3a_d1_build_conflict_register
  (entry_id, opened_by, scope, classification, status, blocked_on, note)
VALUES
  ('CORR-006/CX-15/nothing-rendered-the-old-sentences',
   'CORR-006 Section 4, measured before building',
   'Whether Section 5.16''s retired wording was ever rendered',
   'the instruction is satisfied, but not by a replacement — stated so the record is not misread',
   'open',
   'Founder: note that the Section 5.16 participant notice does not exist as a screen. The corrected '
   || 'wording is loaded and ready; building the notice is separate work.',
   'CX-15 says "Render the corrected text; the old sentences must no longer render anywhere." '
   || 'SEARCHED FIRST: the phrase "artificial intelligence" appears ZERO times in src/, zero times in '
   || 'supabase/migrations/ and zero times in every loaded content version; so does the string '
   || '"5.16"; and T3A-D1-EXEC-001 Section 5.16 is neither on disk nor loaded. '
   || 'SO THERE WAS NO PARTICIPANT NOTICE TO EDIT. The wording that tells every participant how a '
   || 'Stage is administered was never built, and "the old sentences must no longer render anywhere" '
   || 'is true today only because NOTHING renders at all. Reporting CX-15 as "replaced" would be a '
   || 'false statement about participant-facing text, which is why it is said here instead. '
   || 'WHAT WAS BUILT IS THE DURABLE HALF: the corrected text is loaded as issued content so the '
   || 'notice has one approved wording when someone builds it, and both retired sentences are held '
   || 'with their hashes behind a guard that refuses any participant notice containing either. That '
   || 'survives the notice being built later by someone working from the superseded document, which '
   || 'is the realistic way the old wording would come back.'),

  ('CORR-006/CX-15/annex-e-has-no-issued-identifier',
   'CORR-006 Section 4, while loading Annex E',
   'Who named the corrected Section 5.16 object',
   'a naming act the build performed because the instrument did not',
   'open',
   'Founder: confirm T3A-D1-S516-PARTICIPANT-NOTICE-001 as the identifier, or issue one.',
   'Annexes A, B and C each carry an identifier the founder issued — T3A-S1-DELIVERY-SPEC-001, '
   || 'T3A-S1-ADMIN-CONFIG-001, T3A-PARTICIPANT-SAFETY-001. ANNEX E CARRIES NONE. Content is '
   || 'registered by identifier, so the build had to supply one to load it at all, and chose '
   || 'T3A-D1-S516-PARTICIPANT-NOTICE-001. '
   || 'RECORDED RATHER THAN PASSED OVER because an identifier is how an approval, a hash and a '
   || 'citation all name the same text, and a build inventing one is the build naming a governance '
   || 'object. Nothing is blocked: the text and its hashes are what matter to a renderer, and an '
   || 'issued identifier can supersede this one without changing a word of the content. '
   || 'THE FAMILY IS ALSO THE BUILD''S CHOICE: t3a_content_family has no participant_notice value, '
   || 'and adding one would define a new CLASS of content in the schema''s vocabulary, which is a '
   || 'doctrine act. The object is registered as ''configuration'', following Annex C, which is a '
   || 'configuration and carries the crisis line a participant reads.')
ON CONFLICT (entry_id) DO UPDATE SET
  opened_by = EXCLUDED.opened_by, scope = EXCLUDED.scope,
  classification = EXCLUDED.classification, status = EXCLUDED.status,
  blocked_on = EXCLUDED.blocked_on, note = EXCLUDED.note;

-- ---------------------------------------------------------------------
-- 6. The evidence, as rows
-- ---------------------------------------------------------------------

INSERT INTO public.t3a_d1_correction_test
  (correction_test_id, instrument, test_name, fixture, required_result,
   restated_by, supersedes_fixture, why_restated)
VALUES
  ('CX-15-RETIRED-SENTENCES', 'T3A-D1-EXEC-CORR-006 Annex E, CX-15',
   'The retired Section 5.16 sentences render nowhere, and cannot be reintroduced',
   'Every loaded content version, for the measurement; a synthetic notice created inside an aborted '
   || 'transaction, for the refusal.',
   'Zero loaded versions carry either retired sentence. A notice containing one is refused by name; '
   || 'the same notice containing the replacement is accepted.',
   'CX-15', NULL,
   'The measurement is the part that matters: CX-15 reads as an edit, and there was nothing to edit.')
ON CONFLICT (correction_test_id) DO UPDATE SET
  instrument = EXCLUDED.instrument, test_name = EXCLUDED.test_name,
  fixture = EXCLUDED.fixture, required_result = EXCLUDED.required_result,
  restated_by = EXCLUDED.restated_by, supersedes_fixture = EXCLUDED.supersedes_fixture,
  why_restated = EXCLUDED.why_restated;

INSERT INTO public.t3a_d1_correction_test_outcome
  (correction_test_id, outcome, actual_result, build_version, tester, conflict_note)
VALUES
  ('CX-15-RETIRED-SENTENCES', 'pass',
   'scripts/proofs/s516-retired-sentence-proof.sql, self-aborting: '
   || 'noticeWithRetiredSentence=REFUSED_BY_NAME noticeWithReplacement=ACCEPTED '
   || 'updateSmuggling=REFUSED_BY_CONTENT_IMMUTABILITY loadedVersionsCarryingRetiredText=0.',
   '20261078000000', 'Claude Code, automated, non-production environment',
   'TWO THINGS THE RESULT LINE SAYS THAT A BARE "PASS" WOULD HIDE. '
   || 'loadedVersionsCarryingRetiredText=0 read zero BEFORE this work as well: the Section 5.16 '
   || 'notice was never built, so CX-15 had nothing to replace, and what was built is the guard '
   || 'rather than the replacement. '
   || 'updateSmuggling is refused by CONTENT_HISTORY_OVERWRITE — a pre-existing guard making a '
   || 'version body immutable — and NOT by the CX-15 trigger, whose BEFORE UPDATE half is therefore '
   || 'unreachable today. It is kept in case that immutability is ever relaxed, and the distinction '
   || 'is recorded because "refused" and "refused by the control I just built" are different claims.');
