-- =====================================================================
-- T3A-D1-EXEC-CORR-004 executed — AC-12 closes for two of five scopes
-- =====================================================================

set search_path = public;

-- CS-I-43. Per Stage, because a single pass or fail would be untrue
-- either way.
INSERT INTO public.t3a_d1_acceptance_evidence
  (test_id, outcome, actual_result, build_version, tester, executed_at, conflict_note)
VALUES
  ('AC-12', 'pass',
   'CLAIMED for demonstration sources and Stage 1 production; NOT YET CLAIMABLE for Stage 2 '
   || 'production; NOT APPLICABLE for Stage 3 and for Stage 4 while it is disabled. Recorded per '
   || 'Stage under CS-I-43 because a single verdict would misstate every scope. '
   || 'CS-I-32 is what unblocked it, and it amends CS-I-27 — which this build had relied on. '
   || 'There is no single decision point: three determinations resolve from three different '
   || 'fields, and BR-07 already named each. Q-D1-02 from enquiry_point, Q-D1-07 from '
   || 'account_test_point, Q-D1-08a from the decision point stated inside bearing_interest. '
   || 'All six sources carrying a bearing interest resolve exactly as CORR-004 Section 1.2 '
   || 'transcribes them, parsed rather than hand-entered per CS-I-36: SRC-D1-S1-009 R2, '
   || 'SRC-D1-S2-005 B3, SRC-D1-S2-010 B3, SRC-D1-S4-001 B4, SRC-D1-S4-007 B4, and SRC-D1-S3-010 '
   || 'naming its decision point in words so no beat resolves and the determination refuses by '
   || 'name under CS-I-35. '
   || 'CS-I-37 verified: on S1-009, S2-005 and S2-010 the decision point and the enquiry point '
   || 'coincide. CS-I-38 verified: on S4-001 the decision point is B4 and the enquiry B3, '
   || 'distinct, and on S3-010 the enquiry follows the decision. '
   || 'CS-I-33 stands and is untouched: no reference is derived from a pause, and no beat code is '
   || 'assumed to carry a fixed role. CS-20 is why — DEMO-D1-S1-001 pauses at B3 and '
   || 'DEMO-D1-S2-001 at B2.',
   '6254ec5', 'SQL proof and Playwright', now(),
   'Stage 2, 3 and 4 production sources carry no structured sequence. CS-I-42 records that '
   || 'extraction as content authoring rather than a build task, so Stage 2 stays NOT YET '
   || 'CLAIMABLE.'),

  ('AC-30', 'pass',
   'CS-I-25 corrected, and the error was in my search rather than only in the count. There are '
   || 'thirteen Reveal sequence BLOCKS, not thirteen demonstration sources: three demonstration '
   || '(DEMO-D1-S1-001, S2-001, S4-001) and ten Stage 1 production (SRC-D1-S1-001 to S1-010). '
   || 'My earlier pass found two because it searched for "Mentor script" blocks; DEMO-D1-S4-001 '
   || 'carries a "Facilitator card" instead, a Stage 4 panel being facilitated rather than '
   || 'administered one to one. Searching for the thing I expected rather than the thing the '
   || 'inventory named cost the third demonstration sequence and all ten Stage 1 ones. My '
   || 'position that no loaded source carried a sequence held for Stage 2, 3 and 4 and not for '
   || 'Stage 1. '
   || 'CS-31 and CS-32 pass: thirteen sequences loaded, 46 REVEAL beats across the ten Stage 1 '
   || 'sources with role labels mapped, generated by scripts/extract-d1-sequences.mjs which '
   || 'refuses to emit unless the inventory is three plus ten. CS-33 holds: line 4678 is '
   || 'run-together prose and is not loaded. DEMO-D1-S3-001 still carries no sequence and needs '
   || 'none.',
   '6254ec5', 'scripts/extract-d1-sequences.mjs and SQL proof', now(), NULL),

  ('AC-31', 'pass',
   'CS-I-44 to CS-I-48. The content-identity assertion ran across all forty sources, 755 field '
   || 'comparisons, and IT FOUND THREE. Nine fields across SRC-D1-S1-010, SRC-D1-S2-010 and '
   || 'SRC-D1-S3-010 changed rather than extended, so their carry-forward is void under CS-I-45: '
   || 'withdrawn, unservable, logged for re-approval. Thirty-seven carried approvals hold '
   || 'provenance showing basis PARSE_RECOVERY_CORR_003, the version carried from and the '
   || 'assertion result (CS-36). '
   || 'Those three are not soft-wrap recoveries that grew. They are the definitional-run values '
   || 'being replaced by the source''s real data — the second fault CORR-003 fixed — which is a '
   || 'different class of correction, and CS-I-44 is exactly the instrument that tells them '
   || 'apart. '
   || 'CS-37 now runs FIRST in the browser suite: a fixture pinned to a superseded version fails '
   || 'the suite rather than passing it (CS-I-48). Fourteen browser tests green.',
   '6254ec5', 'SQL proof and Playwright', now(),
   'SRC-D1-S1-010, SRC-D1-S2-010 and SRC-D1-S3-010 are UNSERVABLE pending founder re-approval of '
   || 'their corrected transcriptions. This is CS-I-45 working, not a failure to implement it. '
   || 'Two controls were run into and neither routed around: t3a_d1_source_approval takes INSERT '
   || 'only, so the carried rows could not be annotated in place — CS-I-46 is met by making the '
   || 'READ carry the provenance, through t3a_d1_source_approval_standing — and voiding could not '
   || 'delete an approval, so it records a withdrawal, which means STANDING is the latest status '
   || 'per version rather than the existence of an approved row. '
   || 'One self-inflicted fault worth recording: the first run of the assertion scoped itself to '
   || 'every superseded pair, and this content has two supersede generations, so it wrote '
   || 'provenance against the ORIGINAL approvals — marking approvals given directly as '
   || '"carried", the exact misrepresentation CS-I-46 exists to prevent. The tables were rebuilt '
   || 'and the pair scoped to the current version and the one it superseded.');

-- AC-13's evidence is restated: the question it rides on changed.
INSERT INTO public.t3a_d1_acceptance_evidence
  (test_id, outcome, actual_result, build_version, tester, executed_at, conflict_note)
VALUES
  ('AC-13', 'pass',
   'Re-executed against CS-I-32. The assertion no longer rides on Q-D1-08a: SRC-D1-S2-001 '
   || 'carries no bearing interest, so under CS-I-34 Q-D1-08a is NOT SERVED and no control '
   || 'appears — its absence is not a missing state and is not a refusal. Q-D1-02 is the timing '
   || 'determination served on this source, its reference resolving from enquiry_point "B3", and '
   || 'it is PREVENTED and named because the source carries no loaded sequence. The test asserts '
   || 'both: that Q-D1-08a is absent and that Q-D1-02 is refused by name with zero options '
   || 'offered.',
   '6254ec5', 'Playwright, e2e/mentor-cockpit.spec.ts', now(), NULL);
